"""Bounded, durable NFL market automation for Supabase Cron.

Each invocation performs at most one paid league-wide odds request. Durable
reservations make an interrupted request non-replayable, while immutable
database triggers enforce the pre-kickoff evidence boundary independently of
application code.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
import hashlib
import json
import math
import os
from urllib.parse import urlencode, urlparse

from backend.app.database import get_db_connection, using_postgres
from backend.app.services.nfl_product_service import _schedule, current_week_context, nfl_season_year
from backtesting.game_matching import match_game, normalize_team, parse_dt
from nfl_providers import (
    HttpJsonResponse, NFL_SPORT_KEY, ODDS_API_BASE, StructuredHttpError,
    _fetch_json_structured,
)

CHECKPOINTS = ((1440, 30), (360, 15), (60, 5))
MARKETS = ("h2h", "spreads", "totals")
REQUEST_COST = 3
MIN_ACCOUNT_RESERVE = 6
SOURCE_MAX_AGE_SECONDS = 900
ENDPOINT = f"{ODDS_API_BASE}/sports/{NFL_SPORT_KEY}/odds"
JOB_NAME = "smartbets-nfl-active-season"
VAULT_SECRET_NAME = "smartbets_nfl_automation_secret"


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def iso(value: datetime) -> str:
    return value.astimezone(timezone.utc).replace(microsecond=0).isoformat()


def canonical(value) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False)


def digest(value) -> str:
    return hashlib.sha256(canonical(value).encode("utf-8")).hexdigest()


def aware_dt(value) -> datetime | None:
    try:
        raw = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        return parse_dt(value) if raw.tzinfo is not None else None
    except (TypeError, ValueError):
        return None


def _bool_env(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    return default if value is None else value.strip().lower() in {"1", "true", "yes", "on"}


def _row_value(row, key, default=None):
    try:
        return row[key]
    except (KeyError, IndexError, TypeError):
        return default


def initialize() -> None:
    """Create server automation state without exposing tables through the Data API."""
    identifier = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if using_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"
    with get_db_connection() as connection:
        connection.execute("""CREATE TABLE IF NOT EXISTS nfl_automation_state (
            singleton INTEGER PRIMARY KEY CHECK(singleton=1), enabled INTEGER NOT NULL DEFAULT 1,
            active_experiment_key TEXT, last_context_refresh_at TEXT, last_tick_started_at TEXT,
            last_tick_completed_at TEXT, last_status TEXT NOT NULL DEFAULT 'BOOTSTRAP',
            last_error_code TEXT, last_provider_contact_at TEXT, next_due_at TEXT, updated_at TEXT NOT NULL)""")
        connection.execute("""CREATE TABLE IF NOT EXISTS nfl_capture_experiments (
            experiment_key TEXT PRIMARY KEY, season INTEGER NOT NULL, season_type TEXT NOT NULL,
            display_week INTEGER NOT NULL, provider_week INTEGER NOT NULL, status TEXT NOT NULL,
            manifest_json TEXT NOT NULL, manifest_hash TEXT NOT NULL, credits_limit INTEGER NOT NULL,
            credits_reserved INTEGER NOT NULL DEFAULT 0, provider_remaining INTEGER,
            quota_state TEXT NOT NULL DEFAULT 'BOOTSTRAP', created_at TEXT NOT NULL, sealed_at TEXT,
            UNIQUE(season,season_type,display_week))""")
        connection.execute("""CREATE TABLE IF NOT EXISTS nfl_capture_games (
            experiment_key TEXT NOT NULL, game_id TEXT NOT NULL, home_team TEXT NOT NULL,
            away_team TEXT NOT NULL, kickoff TEXT NOT NULL, kickoff_epoch REAL NOT NULL,
            schedule_hash TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'SCHEDULED',
            PRIMARY KEY(experiment_key,game_id), FOREIGN KEY(experiment_key) REFERENCES nfl_capture_experiments(experiment_key))""")
        connection.execute("""CREATE TABLE IF NOT EXISTS nfl_capture_checkpoints (
            experiment_key TEXT NOT NULL, game_id TEXT NOT NULL, offset_minutes INTEGER NOT NULL,
            due_at TEXT NOT NULL, due_epoch REAL NOT NULL, deadline_at TEXT NOT NULL,
            deadline_epoch REAL NOT NULL, state TEXT NOT NULL DEFAULT 'PENDING',
            attempt_count INTEGER NOT NULL DEFAULT 0, last_attempt_at TEXT,
            PRIMARY KEY(experiment_key,game_id,offset_minutes),
            FOREIGN KEY(experiment_key,game_id) REFERENCES nfl_capture_games(experiment_key,game_id))""")
        connection.execute(f"""CREATE TABLE IF NOT EXISTS nfl_capture_requests (
            id {identifier}, request_key TEXT NOT NULL UNIQUE, experiment_key TEXT NOT NULL,
            requested_at TEXT NOT NULL, completed_at TEXT, state TEXT NOT NULL,
            credits_reserved INTEGER NOT NULL, remaining INTEGER, used INTEGER, last_cost INTEGER,
            response_hash TEXT, http_status INTEGER,
            FOREIGN KEY(experiment_key) REFERENCES nfl_capture_experiments(experiment_key))""")
        connection.execute("""CREATE TABLE IF NOT EXISTS nfl_capture_markets (
            capture_key TEXT PRIMARY KEY, experiment_key TEXT NOT NULL, game_id TEXT NOT NULL,
            offset_minutes INTEGER NOT NULL, request_id INTEGER NOT NULL, retrieved_at TEXT NOT NULL,
            stored_at TEXT NOT NULL, kickoff TEXT NOT NULL, cutoff_epoch REAL NOT NULL,
            deadline_epoch REAL NOT NULL, event_id TEXT NOT NULL, bookmaker TEXT NOT NULL,
            market_type TEXT NOT NULL, source_time TEXT NOT NULL, source_epoch REAL NOT NULL,
            retrieved_epoch REAL NOT NULL, outcomes_json TEXT NOT NULL, provenance_json TEXT NOT NULL,
            UNIQUE(experiment_key,game_id,offset_minutes,bookmaker,market_type),
            FOREIGN KEY(request_id) REFERENCES nfl_capture_requests(id),
            FOREIGN KEY(experiment_key,game_id,offset_minutes)
              REFERENCES nfl_capture_checkpoints(experiment_key,game_id,offset_minutes))""")
        connection.execute("""CREATE TABLE IF NOT EXISTS nfl_capture_quotes (
            capture_key TEXT NOT NULL, side TEXT NOT NULL, line REAL, price REAL NOT NULL,
            PRIMARY KEY(capture_key,side), FOREIGN KEY(capture_key) REFERENCES nfl_capture_markets(capture_key))""")
        connection.execute(f"""CREATE TABLE IF NOT EXISTS nfl_automation_events (
            id {identifier}, event_key TEXT NOT NULL UNIQUE, severity TEXT NOT NULL,
            category TEXT NOT NULL, state TEXT NOT NULL, summary TEXT NOT NULL,
            experiment_key TEXT, game_id TEXT, detected_at TEXT NOT NULL, details_json TEXT NOT NULL)""")
        now = iso(utcnow())
        connection.execute("""INSERT INTO nfl_automation_state(singleton,enabled,last_status,updated_at)
            VALUES(1,1,'BOOTSTRAP',?) ON CONFLICT(singleton) DO NOTHING""", (now,))
        if using_postgres():
            for table in (
                "nfl_automation_state", "nfl_capture_experiments", "nfl_capture_games",
                "nfl_capture_checkpoints", "nfl_capture_requests", "nfl_capture_markets",
                "nfl_capture_quotes", "nfl_automation_events",
            ):
                connection.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
                connection.execute(f"REVOKE ALL ON TABLE {table} FROM anon, authenticated")
            connection.execute("CREATE SCHEMA IF NOT EXISTS smartbets_internal")
            connection.execute("REVOKE ALL ON SCHEMA smartbets_internal FROM PUBLIC")
            connection.execute("""CREATE OR REPLACE FUNCTION smartbets_internal.block_immutable_capture()
                RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN
                  RAISE EXCEPTION 'immutable NFL market evidence';
                END $$""")
            connection.execute("""CREATE OR REPLACE FUNCTION smartbets_internal.enforce_pregame_capture()
                RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$ BEGIN
                  IF EXTRACT(EPOCH FROM clock_timestamp()) >= NEW.cutoff_epoch
                     OR NEW.retrieved_epoch >= NEW.cutoff_epoch
                     OR NEW.source_epoch >= NEW.cutoff_epoch
                     OR NEW.source_epoch > NEW.retrieved_epoch
                     OR EXTRACT(EPOCH FROM clock_timestamp()) >= NEW.deadline_epoch
                     OR NEW.retrieved_epoch >= NEW.deadline_epoch THEN
                    RAISE EXCEPTION 'pregame write boundary';
                  END IF;
                  RETURN NEW;
                END $$""")
            connection.execute("""CREATE OR REPLACE FUNCTION smartbets_internal.enforce_pregame_quote()
                RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$
                DECLARE evidence_cutoff DOUBLE PRECISION; evidence_deadline DOUBLE PRECISION; BEGIN
                  SELECT cutoff_epoch,deadline_epoch INTO evidence_cutoff,evidence_deadline
                    FROM nfl_capture_markets WHERE capture_key=NEW.capture_key;
                  IF evidence_cutoff IS NULL
                     OR EXTRACT(EPOCH FROM clock_timestamp()) >= evidence_cutoff
                     OR EXTRACT(EPOCH FROM clock_timestamp()) >= evidence_deadline THEN
                    RAISE EXCEPTION 'pregame write boundary';
                  END IF;
                  RETURN NEW;
                END $$""")
            connection.execute("DROP TRIGGER IF EXISTS nfl_capture_markets_pregame ON nfl_capture_markets")
            connection.execute("""CREATE TRIGGER nfl_capture_markets_pregame BEFORE INSERT ON nfl_capture_markets
                FOR EACH ROW EXECUTE FUNCTION smartbets_internal.enforce_pregame_capture()""")
            connection.execute("DROP TRIGGER IF EXISTS nfl_capture_quotes_pregame ON nfl_capture_quotes")
            connection.execute("""CREATE TRIGGER nfl_capture_quotes_pregame BEFORE INSERT ON nfl_capture_quotes
                FOR EACH ROW EXECUTE FUNCTION smartbets_internal.enforce_pregame_quote()""")
            for table in ("nfl_capture_markets", "nfl_capture_quotes"):
                connection.execute(f"DROP TRIGGER IF EXISTS {table}_immutable_update ON {table}")
                connection.execute(f"DROP TRIGGER IF EXISTS {table}_immutable_delete ON {table}")
                connection.execute(f"CREATE TRIGGER {table}_immutable_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION smartbets_internal.block_immutable_capture()")
                connection.execute(f"CREATE TRIGGER {table}_immutable_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION smartbets_internal.block_immutable_capture()")
            connection.execute("""CREATE OR REPLACE FUNCTION smartbets_internal.protect_nfl_experiment()
                RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN
                  IF OLD.manifest_json IS DISTINCT FROM NEW.manifest_json
                     OR OLD.manifest_hash IS DISTINCT FROM NEW.manifest_hash
                     OR OLD.season IS DISTINCT FROM NEW.season
                     OR OLD.season_type IS DISTINCT FROM NEW.season_type
                     OR OLD.display_week IS DISTINCT FROM NEW.display_week
                     OR OLD.provider_week IS DISTINCT FROM NEW.provider_week
                     OR OLD.credits_limit IS DISTINCT FROM NEW.credits_limit THEN
                    RAISE EXCEPTION 'immutable NFL experiment manifest';
                  END IF;
                  RETURN NEW;
                END $$""")
            connection.execute("DROP TRIGGER IF EXISTS nfl_capture_experiments_protect ON nfl_capture_experiments")
            connection.execute("""CREATE TRIGGER nfl_capture_experiments_protect BEFORE UPDATE ON nfl_capture_experiments
                FOR EACH ROW EXECUTE FUNCTION smartbets_internal.protect_nfl_experiment()""")
            connection.execute("DROP TRIGGER IF EXISTS nfl_capture_games_immutable_update ON nfl_capture_games")
            connection.execute("DROP TRIGGER IF EXISTS nfl_capture_games_immutable_delete ON nfl_capture_games")
            connection.execute("""CREATE TRIGGER nfl_capture_games_immutable_update BEFORE UPDATE ON nfl_capture_games
                FOR EACH ROW EXECUTE FUNCTION smartbets_internal.block_immutable_capture()""")
            connection.execute("""CREATE TRIGGER nfl_capture_games_immutable_delete BEFORE DELETE ON nfl_capture_games
                FOR EACH ROW EXECUTE FUNCTION smartbets_internal.block_immutable_capture()""")


def _event(connection, *, severity: str, category: str, state: str, summary: str,
           experiment_key: str | None = None, game_id: str | None = None, details=None,
           at: datetime | None = None) -> None:
    detected = at or utcnow()
    data = details or {}
    key = digest({"category": category, "state": state, "experiment": experiment_key,
                  "game": game_id, "details": data})
    connection.execute("""INSERT INTO nfl_automation_events(
        event_key,severity,category,state,summary,experiment_key,game_id,detected_at,details_json)
        VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(event_key) DO NOTHING""",
        (key, severity, category, state, summary, experiment_key, game_id, iso(detected), canonical(data)))


def _register_context(connection, context: dict, now: datetime) -> str | None:
    season = int(context["season"])
    phase = str(context["seasonType"])
    week = int(context["week"])
    # The audited 2026 preseason Week 3 experiment is permanently outside this
    # new automation namespace and must never receive another write.
    if (season, phase, week) == (2026, "preseason", 3):
        return None
    if not context.get("hasUpcoming"):
        return None
    games = _schedule(season, week, phase)
    future = []
    for game in games:
        kickoff = aware_dt(game.get("kickoff_time"))
        home, away = normalize_team(game.get("home_team")), normalize_team(game.get("away_team"))
        if (not kickoff or kickoff <= now or game.get("status") != "scheduled" or not home or
                not away or home == away or not game.get("game_id")):
            continue
        future.append({"game_id": str(game["game_id"]), "home_team": home, "away_team": away,
                       "kickoff": iso(kickoff), "kickoff_epoch": kickoff.timestamp(),
                       "schedule_hash": digest(game)})
    if not future:
        return None
    future.sort(key=lambda row: row["game_id"])
    key = f"NFL-{season}-{phase.upper()}-{week}-CAPTURE-v1"
    manifest = {"schema_version": 1, "purpose": "market_coverage_only", "season": season,
                "season_type": phase, "display_week": week,
                "provider_week": int(context.get("providerWeek", week)), "created_at": iso(now),
                "games": future, "checkpoints": CHECKPOINTS, "markets": MARKETS,
                "region": "us", "credits_limit": int(os.getenv("NFL_AUTOMATION_CREDITS_PER_WEEK", "90")),
                "max_source_age_seconds": SOURCE_MAX_AGE_SECONDS, "model_tuning": False}
    connection.execute("""INSERT INTO nfl_capture_experiments(
        experiment_key,season,season_type,display_week,provider_week,status,manifest_json,
        manifest_hash,credits_limit,created_at) VALUES(?,?,?,?,?,'ACTIVE',?,?,?,?)
        ON CONFLICT(season,season_type,display_week) DO NOTHING""",
        (key, season, phase, week, int(context.get("providerWeek", week)), canonical(manifest),
         digest(manifest), manifest["credits_limit"], iso(now)))
    existing = connection.execute("""SELECT experiment_key FROM nfl_capture_experiments
        WHERE season=? AND season_type=? AND display_week=?""", (season, phase, week)).fetchone()
    key = str(_row_value(existing, "experiment_key", key))
    for game in future:
        connection.execute("""INSERT INTO nfl_capture_games(
            experiment_key,game_id,home_team,away_team,kickoff,kickoff_epoch,schedule_hash,status)
            VALUES(?,?,?,?,?,?,?,'SCHEDULED') ON CONFLICT(experiment_key,game_id) DO NOTHING""",
            (key, game["game_id"], game["home_team"], game["away_team"], game["kickoff"],
             game["kickoff_epoch"], game["schedule_hash"]))
        for offset, tolerance in CHECKPOINTS:
            due = datetime.fromtimestamp(game["kickoff_epoch"] - offset * 60, timezone.utc)
            deadline = due + timedelta(minutes=tolerance)
            connection.execute("""INSERT INTO nfl_capture_checkpoints(
                experiment_key,game_id,offset_minutes,due_at,due_epoch,deadline_at,deadline_epoch)
                VALUES(?,?,?,?,?,?,?) ON CONFLICT(experiment_key,game_id,offset_minutes) DO NOTHING""",
                (key, game["game_id"], offset, iso(due), due.timestamp(), iso(deadline), deadline.timestamp()))
    connection.execute("""UPDATE nfl_automation_state SET active_experiment_key=?,
        last_context_refresh_at=?,updated_at=? WHERE singleton=1""", (key, iso(now), iso(now)))
    return key


def _active_experiment(connection, now: datetime, context_resolver=current_week_context) -> str | None:
    state = connection.execute("SELECT * FROM nfl_automation_state WHERE singleton=1").fetchone()
    key = _row_value(state, "active_experiment_key")
    if key:
        latest = connection.execute("SELECT MAX(kickoff_epoch) AS value FROM nfl_capture_games WHERE experiment_key=?", (key,)).fetchone()
        end_epoch = _row_value(latest, "value")
        if end_epoch is not None and now.timestamp() <= float(end_epoch) + 8 * 3600:
            return str(key)
        connection.execute("UPDATE nfl_capture_experiments SET status='SEALED',sealed_at=? WHERE experiment_key=? AND status='ACTIVE'", (iso(now), key))
    context = context_resolver(nfl_season_year(now))
    return _register_context(connection, context, now)


def _header_number(headers, name: str) -> int | None:
    lowered = {str(key).lower(): value for key, value in (headers or {}).items()}
    try:
        value = int(lowered[name.lower()])
        return value if value >= 0 else None
    except (KeyError, TypeError, ValueError):
        return None


def _failure_state(error: StructuredHttpError) -> str:
    remaining = _header_number(error.headers, "x-requests-remaining")
    if remaining == 0 or "usage credits" in str(error.provider_message).lower():
        return "QUOTA_EXHAUSTED"
    if error.status in {401, 403}:
        return "AUTH_ERROR"
    if error.status == 429:
        return "RATE_LIMITED"
    if error.classification == "INVALID_PROVIDER_RESPONSE":
        return "MALFORMED_RESPONSE"
    return "NETWORK_FAILURE" if error.status is None else "UPSTREAM_ERROR"


def _valid_outcomes(market: dict, game) -> list[dict] | None:
    kind, rows = market.get("key"), market.get("outcomes", [])
    if len(rows) != 2:
        return None
    result = []
    for row in rows:
        price, line = row.get("price"), row.get("point")
        if isinstance(price, bool) or not isinstance(price, (float, int)) or not math.isfinite(price) or abs(price) < 100:
            return None
        if kind != "h2h" and (isinstance(line, bool) or not isinstance(line, (float, int)) or not math.isfinite(line)):
            return None
        side = str(row.get("name", ""))
        side = side.lower() if kind == "totals" else normalize_team(side)
        result.append({"side": side, "line": None if kind == "h2h" else line, "price": price})
    expected = {"over", "under"} if kind == "totals" else {game["home_team"], game["away_team"]}
    if {row["side"] for row in result} != expected:
        return None
    if kind == "totals" and (result[0]["line"] != result[1]["line"] or result[0]["line"] <= 0):
        return None
    if kind == "spreads" and abs(result[0]["line"] + result[1]["line"]) > 1e-6:
        return None
    return sorted(result, key=lambda row: row["side"])


def _store_game(connection, checkpoint, events: list, request_id: int,
                retrieved: datetime, clock) -> str:
    game = dict(checkpoint)
    game["kickoff_time"] = game["kickoff"]
    matched = [event for event in events if isinstance(event, dict)
               and match_game(event, [game], tolerance_minutes=180, league="nfl").matched]
    if len(matched) != 1:
        return "NO_MARKET" if not matched else "AMBIGUOUS_EVENT"
    event = matched[0]
    provider_kickoff = aware_dt(event.get("commence_time"))
    if not provider_kickoff or abs(provider_kickoff.timestamp() - float(game["kickoff_epoch"])) > 60:
        if not provider_kickoff:
            return "MALFORMED_RESPONSE"
        return "SCHEDULE_CHANGED"
    cutoff = min(provider_kickoff.timestamp(), float(game["kickoff_epoch"]))
    if max(clock().timestamp(), retrieved.timestamp()) >= min(cutoff, float(game["deadline_epoch"])):
        return "KICKOFF_BLOCKED" if clock().timestamp() >= cutoff else "MISSED_CAPTURE"
    covered, invalid, stale = set(), False, False
    for book in event.get("bookmakers", []):
        for market in book.get("markets", []):
            kind = market.get("key")
            if kind not in MARKETS:
                continue
            source = aware_dt(market.get("last_update") or book.get("last_update"))
            if not source or source > retrieved or source.timestamp() >= cutoff:
                invalid = True
                continue
            age = (retrieved - source).total_seconds()
            if age < 0 or age > SOURCE_MAX_AGE_SECONDS:
                stale = True
                continue
            outcomes = _valid_outcomes(market, game)
            if not outcomes or not book.get("key") or not event.get("id"):
                invalid = True
                continue
            if clock().timestamp() >= min(cutoff, float(game["deadline_epoch"])):
                return "KICKOFF_BLOCKED"
            capture_key = digest({"experiment": game["experiment_key"], "game": game["game_id"],
                                  "checkpoint": game["offset_minutes"], "book": book["key"], "market": kind})
            provenance = {"provider": "the-odds-api", "endpoint": ENDPOINT, "region": "us",
                          "event_id": event["id"], "bookmaker_title": book.get("title"),
                          "match_strategy": "datetime_home_away_league",
                          "manifest_kickoff": game["kickoff"], "provider_kickoff": event["commence_time"],
                          "market_payload_sha256": digest(market)}
            connection.execute("""INSERT INTO nfl_capture_markets(
                capture_key,experiment_key,game_id,offset_minutes,request_id,retrieved_at,stored_at,
                kickoff,cutoff_epoch,deadline_epoch,event_id,bookmaker,market_type,source_time,
                source_epoch,retrieved_epoch,outcomes_json,provenance_json)
                VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(capture_key) DO NOTHING""",
                (capture_key, game["experiment_key"], game["game_id"], game["offset_minutes"], request_id,
                 iso(retrieved), iso(clock()), iso(datetime.fromtimestamp(cutoff, timezone.utc)), cutoff,
                 game["deadline_epoch"], event["id"], book["key"], kind, iso(source), source.timestamp(),
                 retrieved.timestamp(), canonical(outcomes), canonical(provenance)))
            for outcome in outcomes:
                connection.execute("""INSERT INTO nfl_capture_quotes(capture_key,side,line,price)
                    VALUES(?,?,?,?) ON CONFLICT(capture_key,side) DO NOTHING""",
                    (capture_key, outcome["side"], outcome["line"], outcome["price"]))
            covered.add(kind)
    if len(covered) == len(MARKETS):
        return "COMPLETE"
    if covered:
        return "PARTIAL"
    return "STALE_DATA" if stale else "MALFORMED_RESPONSE" if invalid else "NO_MARKET"


def tick(*, clock=utcnow, fetcher=_fetch_json_structured,
         context_resolver=current_week_context, api_key: str | None = None) -> dict:
    """Run one safe serverless tick; never loop or regenerate model artifacts."""
    if not using_postgres() and os.getenv("PYTEST_CURRENT_TEST") is None:
        raise RuntimeError("Server automation requires persistent PostgreSQL")
    initialize()
    now = clock()
    with get_db_connection() as connection:
        if using_postgres():
            locked = connection.execute("SELECT pg_try_advisory_xact_lock(748219307) AS locked").fetchone()
            if not bool(_row_value(locked, "locked", False)):
                return {"state": "ALREADY_RUNNING", "network_contacted": False}
        state = connection.execute("SELECT * FROM nfl_automation_state WHERE singleton=1").fetchone()
        if not bool(int(_row_value(state, "enabled", 0))) or not _bool_env("NFL_AUTOMATION_ENABLED"):
            return {"state": "DISABLED", "network_contacted": False}
        connection.execute("""UPDATE nfl_automation_state SET last_tick_started_at=?,
            last_status='RUNNING',last_error_code=NULL,updated_at=? WHERE singleton=1""", (iso(now), iso(now)))
        key = _active_experiment(connection, now, context_resolver)
        if not key:
            connection.execute("""UPDATE nfl_automation_state SET active_experiment_key=NULL,
                last_tick_completed_at=?,last_status='OFFSEASON',updated_at=? WHERE singleton=1""",
                (iso(now), iso(now)))
            return {"state": "OFFSEASON", "network_contacted": False}
        connection.execute("""UPDATE nfl_capture_checkpoints SET state='MISSED_CAPTURE'
            WHERE experiment_key=? AND state='PENDING' AND deadline_epoch<=?""", (key, now.timestamp()))
        due = connection.execute("""SELECT c.*,g.home_team,g.away_team,g.kickoff,g.kickoff_epoch
            FROM nfl_capture_checkpoints c JOIN nfl_capture_games g
              ON g.experiment_key=c.experiment_key AND g.game_id=c.game_id
            WHERE c.experiment_key=? AND c.state='PENDING' AND c.due_epoch<=?
              AND c.deadline_epoch>? AND g.kickoff_epoch>?
            ORDER BY c.due_epoch,c.game_id""", (key, now.timestamp(), now.timestamp(), now.timestamp())).fetchall()
        next_row = connection.execute("""SELECT MIN(due_at) AS value FROM nfl_capture_checkpoints
            WHERE experiment_key=? AND state='PENDING'""", (key,)).fetchone()
        next_due = _row_value(next_row, "value")
        if not due:
            connection.execute("""UPDATE nfl_automation_state SET last_tick_completed_at=?,
                last_status='IDLE',next_due_at=?,updated_at=? WHERE singleton=1""",
                (iso(now), next_due, iso(now)))
            return {"state": "IDLE", "experiment": key, "next_due_at": next_due, "network_contacted": False}
        experiment = connection.execute("SELECT * FROM nfl_capture_experiments WHERE experiment_key=?", (key,)).fetchone()
        remaining = _row_value(experiment, "provider_remaining")
        covered_rows = connection.execute("""SELECT DISTINCT game_id FROM nfl_capture_markets
            WHERE experiment_key=?""", (key,)).fetchall()
        covered_games = {row["game_id"] for row in covered_rows}
        future_first = connection.execute("""SELECT game_id,MIN(due_epoch) AS first_due
            FROM nfl_capture_checkpoints WHERE experiment_key=? AND state='PENDING' AND due_epoch>?
              AND game_id NOT IN (SELECT DISTINCT game_id FROM nfl_capture_markets WHERE experiment_key=?)
            GROUP BY game_id""", (key, now.timestamp(), key)).fetchall()
        breadth_reserve = REQUEST_COST * len({_row_value(row, "first_due") for row in future_first})
        available = int(experiment["credits_limit"]) - int(_row_value(experiment, "credits_reserved", 0))
        if remaining is not None:
            available = min(available, max(0, int(remaining) - MIN_ACCOUNT_RESERVE))
        if (breadth_reserve and all(row["game_id"] in covered_games for row in due)
                and available - REQUEST_COST < breadth_reserve):
            for row in due:
                connection.execute("""UPDATE nfl_capture_checkpoints SET state='BREADTH_PRIORITY'
                    WHERE experiment_key=? AND game_id=? AND offset_minutes=?""",
                    (key, row["game_id"], row["offset_minutes"]))
            connection.execute("""UPDATE nfl_automation_state SET last_tick_completed_at=?,
                last_status='BREADTH_PRIORITY',updated_at=? WHERE singleton=1""", (iso(now), iso(now)))
            return {"state": "BREADTH_PRIORITY", "network_contacted": False,
                    "reserved_for_uncovered_games": breadth_reserve}
        stop = None
        key_value = api_key if api_key is not None else os.getenv("THE_ODDS_API_KEY") or os.getenv("ODDS_API_KEY")
        if not key_value:
            stop = "AUTH_ERROR"
        elif int(_row_value(experiment, "credits_reserved", 0)) + REQUEST_COST > int(experiment["credits_limit"]):
            stop = "BUDGET_EXHAUSTED"
        elif _row_value(experiment, "quota_state") in {"AUTH_ERROR", "QUOTA_EXHAUSTED", "QUOTA_UNKNOWN", "COST_CHANGED"}:
            stop = str(experiment["quota_state"])
        elif remaining is not None and int(remaining) < REQUEST_COST + MIN_ACCOUNT_RESERVE:
            stop = "QUOTA_EXHAUSTED"
        if stop:
            connection.execute("""UPDATE nfl_automation_state SET last_tick_completed_at=?,last_status=?,
                last_error_code=?,updated_at=? WHERE singleton=1""", (iso(now), stop, stop, iso(now)))
            _event(connection, severity="CRITICAL" if stop == "AUTH_ERROR" else "WARNING",
                   category="PROVIDER", state=stop, summary="NFL market capture is blocked.",
                   experiment_key=key, at=now)
            return {"state": stop, "due_games": len(due), "network_contacted": False}
        request_key = digest({"experiment": key, "due": sorted(
            (row["game_id"], int(row["offset_minutes"])) for row in due)})
        params = (request_key, key, iso(now), "IN_FLIGHT", REQUEST_COST)
        if using_postgres():
            request = connection.execute("""INSERT INTO nfl_capture_requests(
                request_key,experiment_key,requested_at,state,credits_reserved) VALUES(?,?,?,?,?)
                ON CONFLICT(request_key) DO NOTHING RETURNING id""", params).fetchone()
            request_id = _row_value(request, "id")
        else:
            cursor = connection.execute("""INSERT INTO nfl_capture_requests(
                request_key,experiment_key,requested_at,state,credits_reserved) VALUES(?,?,?,?,?)
                ON CONFLICT(request_key) DO NOTHING""", params)
            request_id = cursor.lastrowid
        if not request_id:
            return {"state": "ALREADY_RESERVED", "network_contacted": False}
        connection.execute("""UPDATE nfl_capture_experiments SET credits_reserved=credits_reserved+?,
            quota_state='QUOTA_UNKNOWN' WHERE experiment_key=?""", (REQUEST_COST, key))
        for row in due:
            connection.execute("""UPDATE nfl_capture_checkpoints SET state='IN_FLIGHT',
                attempt_count=attempt_count+1,last_attempt_at=? WHERE experiment_key=? AND game_id=? AND offset_minutes=?""",
                (iso(now), key, row["game_id"], row["offset_minutes"]))
    params = {"apiKey": key_value, "regions": "us", "markets": ",".join(MARKETS), "oddsFormat": "american"}
    response, provider_state = None, "HEALTHY"
    try:
        response = fetcher(ENDPOINT + "?" + urlencode(params), timeout=20)
        if not isinstance(response, HttpJsonResponse) or not isinstance(response.payload, list):
            provider_state = "MALFORMED_RESPONSE"
        else:
            canonical(response.payload)
    except StructuredHttpError as error:
        provider_state = _failure_state(error)
        response = HttpJsonResponse([], error.status, error.headers)
    except (OSError, TimeoutError):
        provider_state = "NETWORK_FAILURE"
    except (TypeError, ValueError):
        provider_state = "MALFORMED_RESPONSE"
    retrieved = clock()
    headers = response.headers if isinstance(response, HttpJsonResponse) else {}
    remaining = _header_number(headers, "x-requests-remaining")
    used = _header_number(headers, "x-requests-used")
    cost = _header_number(headers, "x-requests-last")
    quota = ("COST_CHANGED" if cost is not None and cost > REQUEST_COST else
             provider_state if provider_state in {"AUTH_ERROR", "QUOTA_EXHAUSTED"} else
             "QUOTA_UNKNOWN" if remaining is None else "KNOWN")
    with get_db_connection() as connection:
        connection.execute("""UPDATE nfl_capture_experiments SET provider_remaining=?,quota_state=?
            WHERE experiment_key=?""", (remaining, quota, key))
        connection.execute("""UPDATE nfl_capture_requests SET completed_at=?,state=?,remaining=?,used=?,
            last_cost=?,response_hash=?,http_status=? WHERE id=?""",
            (iso(retrieved), provider_state, remaining, used, cost,
             digest(response.payload) if provider_state == "HEALTHY" else None,
             response.status if isinstance(response, HttpJsonResponse) else None, request_id))
        states = {}
        for original in due:
            row = dict(original)
            result = provider_state
            if provider_state == "HEALTHY":
                try:
                    result = _store_game(connection, row, response.payload, request_id, retrieved, clock)
                except Exception as error:
                    result = "KICKOFF_BLOCKED" if "pregame write boundary" in str(error) else "MALFORMED_RESPONSE"
            connection.execute("""UPDATE nfl_capture_checkpoints SET state=?
                WHERE experiment_key=? AND game_id=? AND offset_minutes=?""",
                (result, key, row["game_id"], row["offset_minutes"]))
            states[row["game_id"]] = result
        connection.execute("""UPDATE nfl_automation_state SET last_tick_completed_at=?,last_status=?,
            last_error_code=?,last_provider_contact_at=?,updated_at=? WHERE singleton=1""",
            (iso(retrieved), provider_state, None if provider_state == "HEALTHY" else provider_state,
             iso(retrieved), iso(retrieved)))
        if provider_state != "HEALTHY":
            _event(connection, severity="WARNING", category="PROVIDER", state=provider_state,
                   summary="The NFL odds provider request did not complete successfully.", experiment_key=key,
                   details={"http_status": response.status if isinstance(response, HttpJsonResponse) else None}, at=retrieved)
    return {"state": provider_state, "experiment": key, "request_id": request_id,
            "reserved_credits": REQUEST_COST, "games": states, "quota_state": quota,
            "remaining": remaining, "network_contacted": True}


def status() -> dict:
    initialize()
    with get_db_connection() as connection:
        state = connection.execute("SELECT * FROM nfl_automation_state WHERE singleton=1").fetchone()
        key = _row_value(state, "active_experiment_key")
        experiment = connection.execute("SELECT * FROM nfl_capture_experiments WHERE experiment_key=?", (key,)).fetchone() if key else None
        counts = connection.execute("""SELECT state,COUNT(*) AS count FROM nfl_capture_checkpoints
            WHERE experiment_key=? GROUP BY state ORDER BY state""", (key,)).fetchall() if key else []
        games = connection.execute("""SELECT COUNT(*) AS total,
            COUNT(DISTINCT CASE WHEN EXISTS(SELECT 1 FROM nfl_capture_markets m
              WHERE m.experiment_key=g.experiment_key AND m.game_id=g.game_id) THEN game_id END) AS covered
            FROM nfl_capture_games g WHERE experiment_key=?""", (key,)).fetchone() if key else None
        alerts = connection.execute("""SELECT severity,category,state,summary,game_id,detected_at
            FROM nfl_automation_events WHERE experiment_key=? ORDER BY detected_at DESC LIMIT 25""", (key,)).fetchall() if key else []
        job, latest_run = None, None
        if using_postgres():
            job = connection.execute("SELECT jobid,jobname,schedule,active FROM cron.job WHERE jobname=?", (JOB_NAME,)).fetchone()
            if job:
                latest_run = connection.execute("""SELECT status,start_time,end_time,return_message
                    FROM cron.job_run_details WHERE jobid=? ORDER BY start_time DESC LIMIT 1""",
                    (job["jobid"],)).fetchone()
    return {"scheduler": "supabase_cron", "enabled": _bool_env("NFL_AUTOMATION_ENABLED"),
            "state": dict(state) if state else None, "experiment": dict(experiment) if experiment else None,
            "checkpoint_counts": {row["state"]: row["count"] for row in counts},
            "game_coverage": dict(games) if games else {"total": 0, "covered": 0},
            "alerts": [dict(row) for row in alerts], "publishing_enabled": False,
            "model_mutation_enabled": False,
            "cron_job": dict(job) if job else None,
            "latest_cron_run": dict(latest_run) if latest_run else None}


def install_supabase_cron(*, base_url: str, secret: str) -> dict:
    """Idempotently install the five-minute pg_cron job with its bearer in Vault."""
    if not using_postgres():
        raise RuntimeError("Supabase Cron installation requires PostgreSQL")
    parsed = urlparse(base_url)
    if parsed.scheme != "https" or not parsed.netloc or parsed.path not in {"", "/"}:
        raise ValueError("NFL_AUTOMATION_BASE_URL must be an HTTPS origin")
    if len(secret) < 32:
        raise ValueError("NFL_AUTOMATION_SECRET must contain at least 32 characters")
    target = base_url.rstrip("/") + "/api/cron/nfl-active-season"
    with get_db_connection() as connection:
        connection.execute("CREATE EXTENSION IF NOT EXISTS pg_cron")
        connection.execute("CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions")
        connection.execute("CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault")
        existing = connection.execute("SELECT id FROM vault.secrets WHERE name=?", (VAULT_SECRET_NAME,)).fetchone()
        if existing:
            connection.execute("SELECT vault.update_secret(?,?,?,?)", (_row_value(existing, "id"), secret,
                               VAULT_SECRET_NAME, "Bearer for SmartBetSports bounded NFL automation"))
        else:
            connection.execute("SELECT vault.create_secret(?,?,?)", (secret, VAULT_SECRET_NAME,
                               "Bearer for SmartBetSports bounded NFL automation"))
        command = """SELECT net.http_post(
            url := '{target}',
            headers := jsonb_build_object(
              'Content-Type','application/json',
              'Authorization','Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name='{vault_name}')
            ),
            body := '{{}}'::jsonb,
            timeout_milliseconds := 25000
          );""".format(target=target.replace("'", "''"), vault_name=VAULT_SECRET_NAME)
        connection.execute("SELECT cron.schedule(?,?,?)", (JOB_NAME, "*/5 * * * *", command))
        job = connection.execute("SELECT jobid,jobname,schedule,active FROM cron.job WHERE jobname=?", (JOB_NAME,)).fetchone()
    return {"installed": True, "job": dict(job) if job else None, "target": target,
            "secret_storage": "supabase_vault", "secret_exposed": False}
