"""Deterministic NFL production lifecycle: freeze, settle, benchmark, and audit.

This module never changes ``nfl_game_predictions``.  It copies the immutable
pregame evidence into an auditable lifecycle row and updates settlement-only
columns after a verified provider final arrives.
"""
from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
import hashlib
import json
import logging
from typing import Any, Callable
from uuid import uuid4
from pathlib import Path

from backend.app.database import get_db_connection, table_exists, using_postgres
from backend.app.services.nfl_game_service import get_nfl_game_detail
from backend.app.services.nfl_product_service import _initialize_predictions, _schedule
from backend.app.services.parlay_history_service import initialize_parlay_history_database
from nfl_parlay_builder import build_nfl_parlay
from nfl_parlay_grader import _grade_player_leg, _grade_team_leg, _overall_status, TEAM_MARKET_ALIASES

logger = logging.getLogger(__name__)
PROFILES = ("SAFE", "BALANCED", "AGGRESSIVE")
FINAL = {"final", "final-ot", "completed"}


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _dt(value: Any) -> datetime:
    return datetime.fromisoformat(str(value).replace("Z", "+00:00")).astimezone(timezone.utc)


def _json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)


def _hash(value: Any) -> str:
    return hashlib.sha256(_json(value).encode("utf-8")).hexdigest()


def _gid(value: Any) -> str:
    text = str(value or "")
    return text if text.startswith("espn-") else f"espn-{text}"


def initialize() -> None:
    _initialize_predictions()
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if using_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"
    with get_db_connection() as connection:
        connection.execute(f"""CREATE TABLE IF NOT EXISTS nfl_prediction_history (
            id {identity}, prediction_id BIGINT NOT NULL UNIQUE, user_id BIGINT NOT NULL,
            sport TEXT NOT NULL, league TEXT NOT NULL, season INTEGER NOT NULL,
            season_type TEXT NOT NULL, week INTEGER NOT NULL, game_id TEXT NOT NULL,
            kickoff_time TEXT NOT NULL, away_team TEXT, home_team TEXT,
            predicted_winner TEXT NOT NULL, model_probability REAL, betting_edge REAL,
            market_odds INTEGER, model_version TEXT NOT NULL, data_version TEXT,
            generated_at TEXT NOT NULL, source_provider TEXT, frozen_prediction_hash TEXT NOT NULL,
            settlement_status TEXT NOT NULL DEFAULT 'PENDING', away_score INTEGER,
            home_score INTEGER, actual_winner TEXT, final_provider TEXT,
            final_source_timestamp TEXT, settled_at TEXT, settlement_reason TEXT,
            created_at TEXT NOT NULL, updated_at TEXT NOT NULL)""")
        connection.execute("CREATE INDEX IF NOT EXISTS idx_nfl_prediction_history_week ON nfl_prediction_history(season,season_type,week,game_id)")
        connection.execute("CREATE INDEX IF NOT EXISTS idx_nfl_prediction_history_user ON nfl_prediction_history(user_id,settlement_status,generated_at)")
        connection.execute(f"""CREATE TABLE IF NOT EXISTS nfl_game_result_snapshots (
            id {identity}, game_id TEXT NOT NULL UNIQUE, season INTEGER NOT NULL,
            season_type TEXT NOT NULL, week INTEGER NOT NULL, kickoff_time TEXT NOT NULL,
            away_team TEXT NOT NULL, home_team TEXT NOT NULL, away_score INTEGER,
            home_score INTEGER, game_status TEXT NOT NULL, team_stats_json TEXT NOT NULL,
            player_stats_json TEXT NOT NULL, provider TEXT NOT NULL,
            provider_timestamp TEXT, retrieved_at TEXT NOT NULL, source_hash TEXT NOT NULL)""")
        connection.execute(f"""CREATE TABLE IF NOT EXISTS nfl_sgp_benchmarks (
            id {identity}, benchmark_key TEXT NOT NULL UNIQUE, game_id TEXT NOT NULL,
            season INTEGER NOT NULL, season_type TEXT NOT NULL, week INTEGER NOT NULL,
            profile TEXT NOT NULL, generated_at TEXT NOT NULL, kickoff_time TEXT NOT NULL,
            model_version TEXT NOT NULL, data_version TEXT, source_prediction_id BIGINT,
            source_hash TEXT NOT NULL, ticket_status TEXT NOT NULL,
            no_bet_reason TEXT, combined_odds INTEGER, estimated_probability REAL,
            recommendation_score REAL, legs_json TEXT NOT NULL, graded_at TEXT,
            UNIQUE(game_id,profile,model_version))""")
        connection.execute("CREATE INDEX IF NOT EXISTS idx_nfl_sgp_benchmark_week ON nfl_sgp_benchmarks(season,season_type,week,profile,ticket_status)")
        connection.execute(f"""CREATE TABLE IF NOT EXISTS nfl_sgp_benchmark_legs (
            id {identity}, benchmark_id BIGINT NOT NULL, leg_index INTEGER NOT NULL,
            market_type TEXT NOT NULL, player TEXT, team TEXT, side TEXT, line REAL,
            odds INTEGER, model_probability REAL, recommendation_score REAL,
            metadata_json TEXT NOT NULL, result_status TEXT NOT NULL DEFAULT 'PENDING',
            actual_value REAL, graded_at TEXT, UNIQUE(benchmark_id,leg_index))""")
        connection.execute("CREATE INDEX IF NOT EXISTS idx_nfl_sgp_leg_market ON nfl_sgp_benchmark_legs(market_type,result_status)")
        connection.execute(f"""CREATE TABLE IF NOT EXISTS nfl_production_audits (
            id {identity}, audit_id TEXT NOT NULL UNIQUE, league TEXT NOT NULL,
            season INTEGER NOT NULL, season_type TEXT NOT NULL, week INTEGER NOT NULL,
            result TEXT NOT NULL, critical_errors INTEGER NOT NULL, warnings INTEGER NOT NULL,
            report_json TEXT NOT NULL, created_at TEXT NOT NULL)""")
        connection.execute("CREATE INDEX IF NOT EXISTS idx_nfl_production_audit_week ON nfl_production_audits(season,season_type,week,created_at)")
        if using_postgres():
            for table in ("nfl_prediction_history", "nfl_game_result_snapshots", "nfl_sgp_benchmarks", "nfl_sgp_benchmark_legs", "nfl_production_audits"):
                connection.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
                connection.execute(f"REVOKE ALL ON TABLE {table} FROM anon, authenticated")


def capture_prediction_history(*, season: int, season_type: str, week: int, schedule: list[dict] | None = None) -> dict:
    """Copy genuine pregame snapshots into immutable history rows, once."""
    initialize()
    schedule = schedule if schedule is not None else _schedule(season, week, season_type)
    games = {_gid(row.get("game_id") or row.get("id")): row for row in schedule}
    inserted, rejected = 0, []
    with get_db_connection() as connection:
        rows = connection.execute(
            "SELECT * FROM nfl_game_predictions WHERE season=? AND season_type=? AND display_week=? ORDER BY id",
            (season, season_type, week),
        ).fetchall()
        for row in rows:
            game = games.get(_gid(row["game_id"]))
            kickoff = (game or {}).get("kickoff_time") or row["kickoff_time"]
            if _dt(row["generated_at"]) >= _dt(kickoff):
                rejected.append({"predictionId": row["id"], "reason": "generated_at_or_after_kickoff"})
                continue
            prediction = json.loads(row["prediction_json"])
            winner = prediction.get("winner")
            if not winner:
                rejected.append({"predictionId": row["id"], "reason": "missing_predicted_winner"})
                continue
            market = prediction.get("market") or {}
            home = (game or {}).get("home_team")
            away = (game or {}).get("away_team")
            price = market.get("homeOdds") if winner == home else market.get("awayOdds") if winner == away else None
            frozen_hash = _hash(prediction)
            cursor = connection.execute("""INSERT INTO nfl_prediction_history
                (prediction_id,user_id,sport,league,season,season_type,week,game_id,kickoff_time,
                 away_team,home_team,predicted_winner,model_probability,betting_edge,market_odds,
                 model_version,data_version,generated_at,source_provider,frozen_prediction_hash,
                 settlement_status,created_at,updated_at)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                ON CONFLICT(prediction_id) DO NOTHING""",
                (row["id"], row["user_id"], "NFL", "NFL", season, season_type, week,
                 _gid(row["game_id"]), kickoff, away, home, winner,
                 prediction.get("winProbability"), prediction.get("edge"), price,
                 row["model_version"], prediction.get("dataAsOf"), row["generated_at"],
                 row.get("provider") if hasattr(row, "get") else row["provider"], frozen_hash,
                 "PENDING", _now(), _now()))
            inserted += int(bool(cursor.rowcount))
    logger.info("nfl_prediction_history_capture %s", _json({"season": season, "seasonType": season_type, "week": week, "inserted": inserted, "rejected": rejected}))
    return {"inserted": inserted, "rejected": rejected}


def _actual_player_stats(detail: dict) -> dict[str, dict[str, Any]]:
    output: dict[str, dict[str, Any]] = defaultdict(dict)
    group_prefix = {"passing": "PASS", "rushing": "RUSH", "receiving": "REC"}
    aliases = {
        ("passing", "YDS"): "PASS_YDS", ("passing", "TD"): "PASS_TDS",
        ("passing", "INT"): "PASS_INT", ("rushing", "YDS"): "RUSH_YDS",
        ("receiving", "YDS"): "REC_YDS", ("receiving", "REC"): "RECEPTIONS",
        ("rushing", "TD"): "ANYTIME_TD", ("receiving", "TD"): "ANYTIME_TD",
    }
    for group in detail.get("actuals", {}).get("playerGroups", []):
        name = group.get("group")
        if name not in group_prefix:
            continue
        for player in group.get("items", []):
            target = output[str(player.get("playerName") or "")]
            for label, value in (player.get("stats") or {}).items():
                key = aliases.get((name, str(label).upper()))
                if not key or not isinstance(value, (int, float)):
                    continue
                if key == "ANYTIME_TD":
                    target[key] = float(target.get(key, 0)) + float(value)
                else:
                    target[key] = value
    return dict(output)


def persist_final(detail: dict) -> bool:
    initialize()
    game = detail.get("game") or {}
    if str(game.get("status") or "").lower() not in FINAL:
        return False
    if game.get("awayScore") is None or game.get("homeScore") is None:
        return False
    payload = {
        "game": game, "teamStats": detail.get("actuals", {}).get("teamStats") or [],
        "playerStats": _actual_player_stats(detail),
    }
    gid = _gid(game.get("id"))
    with get_db_connection() as connection:
        existing = connection.execute("SELECT source_hash FROM nfl_game_result_snapshots WHERE game_id=?", (gid,)).fetchone()
        source_hash = _hash(payload)
        if existing and existing["source_hash"] == source_hash:
            return False
        phase = str(game.get("seasonPhase") or "regular")
        phase = "regular" if phase == "regular_season" else phase
        values = (gid, int(game["season"]), phase, int(game.get("week") or 0),
                  game["startTimeUtc"], game["awayTeam"]["abbreviation"], game["homeTeam"]["abbreviation"],
                  int(game["awayScore"]), int(game["homeScore"]), "FINAL", _json(payload["teamStats"]),
                  _json(payload["playerStats"]), "espn", game.get("statusUpdatedAt"), _now(), source_hash)
        connection.execute("""INSERT INTO nfl_game_result_snapshots
            (game_id,season,season_type,week,kickoff_time,away_team,home_team,away_score,home_score,
             game_status,team_stats_json,player_stats_json,provider,provider_timestamp,retrieved_at,source_hash)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(game_id) DO UPDATE SET away_score=excluded.away_score,home_score=excluded.home_score,
            game_status=excluded.game_status,team_stats_json=excluded.team_stats_json,
            player_stats_json=excluded.player_stats_json,provider_timestamp=excluded.provider_timestamp,
            retrieved_at=excluded.retrieved_at,source_hash=excluded.source_hash""", values)
    logger.info("nfl_game_final_persisted %s", _json({"gameId": gid, "season": game.get("season"), "week": game.get("week")}))
    return True


def settle_predictions(*, season: int, season_type: str, week: int) -> dict:
    initialize()
    settled, already = 0, 0
    with get_db_connection() as connection:
        rows = connection.execute("""SELECT h.*,r.away_score AS result_away_score,r.home_score AS result_home_score,
            r.away_team AS result_away_team,r.home_team AS result_home_team,r.provider,r.provider_timestamp,r.retrieved_at
            FROM nfl_prediction_history h JOIN nfl_game_result_snapshots r ON r.game_id=h.game_id
            WHERE h.season=? AND h.season_type=? AND h.week=?""", (season, season_type, week)).fetchall()
        for row in rows:
            if row["settlement_status"] != "PENDING":
                already += 1
                continue
            away_score, home_score = int(row["result_away_score"]), int(row["result_home_score"])
            actual = None if away_score == home_score else row["result_home_team"] if home_score > away_score else row["result_away_team"]
            status = "PUSH" if actual is None else "WON" if row["predicted_winner"] == actual else "LOST"
            connection.execute("""UPDATE nfl_prediction_history SET settlement_status=?,away_score=?,home_score=?,
                actual_winner=?,final_provider=?,final_source_timestamp=?,settled_at=?,settlement_reason=?,updated_at=?
                WHERE id=? AND settlement_status='PENDING'""",
                (status, away_score, home_score, actual, row["provider"], row["provider_timestamp"] or row["retrieved_at"],
                 _now(), "verified_provider_final", _now(), row["id"]))
            settled += 1
            logger.info("nfl_prediction_settled %s", _json({"gameId": row["game_id"], "predictionId": row["prediction_id"], "result": status}))
    return {"settled": settled, "alreadySettled": already}


def _leg_dict(leg: Any) -> dict:
    data = dict(getattr(leg, "__dict__", {}) or leg)
    sport = data.get("sport")
    data["sport"] = getattr(sport, "value", sport)
    prediction = str(data.get("prediction") or "")
    data["side"] = "under" if " under " in f" {prediction.lower()} " else "over" if " over " in f" {prediction.lower()} " else data.get("side")
    return data


def generate_benchmarks(*, season: int, season_type: str, week: int, schedule: list[dict] | None = None,
                        clock: Callable[[], datetime] | None = None,
                        parlay_builder: Callable[..., Any] = build_nfl_parlay,
                        max_games: int | None = None, max_tickets: int | None = None) -> dict:
    """Freeze at most one game's missing profile tickets per worker tick by default."""
    initialize()
    now = (clock or (lambda: datetime.now(timezone.utc)))()
    schedule = schedule if schedule is not None else _schedule(season, week, season_type)
    created, no_bet, skipped, games_started = 0, 0, 0, 0
    for game in schedule:
        gid = _gid(game.get("game_id") or game.get("id"))
        kickoff = game.get("kickoff_time") or game.get("startTimeUtc")
        if str(game.get("status") or "scheduled").lower() != "scheduled" or not kickoff or now >= _dt(kickoff):
            continue
        with get_db_connection() as connection:
            existing = {r["profile"] for r in connection.execute("SELECT profile FROM nfl_sgp_benchmarks WHERE game_id=?", (gid,)).fetchall()}
            source = connection.execute("""SELECT id,model_version,prediction_json,generated_at FROM nfl_game_predictions
                WHERE game_id=? AND generated_at<? ORDER BY CASE WHEN user_id=0 THEN 0 ELSE 1 END,id LIMIT 1""", (gid, kickoff)).fetchone()
        missing = [profile for profile in PROFILES if profile not in existing]
        if not missing:
            continue
        if not source:
            skipped += len(missing)
            continue
        source_payload = json.loads(source["prediction_json"])
        game_started = False
        for profile in missing:
            if now >= _dt(kickoff):
                game_started = True
                break
            try:
                result = parlay_builder(profile, game_teams=(game["home_team"], game["away_team"]), allow_sample=False)
                legs = [_leg_dict(leg) for leg in result.parlay.legs]
                market_verified = bool(legs) and all(
                    leg.get("provider") == "the-odds-api" and leg.get("bookmaker") and leg.get("event_id")
                    and leg.get("line") is not None and leg.get("odds") is not None
                    and leg.get("market_timestamp") and _dt(leg["market_timestamp"]) < _dt(kickoff)
                    for leg in legs
                )
                if legs and not market_verified:
                    legs = []
                    reason = "Verified pregame market provenance was incomplete; no benchmark ticket was frozen."
                else:
                    reason = None if legs else str(result.notes or "Insufficient verified markets for this profile.")
            except Exception as exc:
                logger.warning("nfl_sgp_generation_provider_failure %s", _json({"gameId": gid, "profile": profile, "error": type(exc).__name__}))
                # Provider failures are retryable and must not be frozen as NO_BET.
                skipped += 1
                continue
            generated_at = _now()
            if _dt(generated_at) >= _dt(kickoff):
                games_started += 1
                break
            source_hash = _hash({"prediction": source_payload, "legs": legs, "gameId": gid, "profile": profile})
            key = _hash({"gameId": gid, "profile": profile, "modelVersion": source["model_version"]})
            recommendation = (sum(float(leg.get("confidence") or 0) for leg in legs) / len(legs)) if legs else None
            with get_db_connection() as connection:
                row = connection.execute("""INSERT INTO nfl_sgp_benchmarks
                    (benchmark_key,game_id,season,season_type,week,profile,generated_at,kickoff_time,
                     model_version,data_version,source_prediction_id,source_hash,ticket_status,no_bet_reason,
                     combined_odds,estimated_probability,recommendation_score,legs_json)
                    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(benchmark_key) DO NOTHING RETURNING id""",
                    (key, gid, season, season_type, week, profile, generated_at, kickoff, source["model_version"],
                     source_payload.get("dataAsOf"), source["id"], source_hash, "PENDING" if legs else "NO_BET", reason,
                     result.estimated_odds if legs else None, result.combined_probability if legs else None,
                     recommendation, _json(legs))).fetchone()
                if not row:
                    continue
                benchmark_id = row["id"]
                for index, leg in enumerate(legs):
                    market = str(leg.get("stat_type") or leg.get("market") or "UNKNOWN").upper()
                    connection.execute("""INSERT INTO nfl_sgp_benchmark_legs
                        (benchmark_id,leg_index,market_type,player,team,side,line,odds,model_probability,
                         recommendation_score,metadata_json,result_status)
                        VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(benchmark_id,leg_index) DO NOTHING""",
                        (benchmark_id, index, market, leg.get("player"), leg.get("team"), leg.get("side"),
                         leg.get("line"), leg.get("odds"), (float(leg.get("confidence")) / 100 if leg.get("confidence") is not None else None),
                         leg.get("confidence"), _json(leg), "PENDING"))
            created += 1
            no_bet += int(not legs)
            logger.info("nfl_sgp_benchmark_created %s", _json({"gameId": gid, "profile": profile, "status": "PENDING" if legs else "NO_BET", "legs": len(legs)}))
            if max_tickets is not None and created >= max_tickets:
                return {"created": created, "noBet": no_bet, "retryableSkipped": skipped}
        if game_started:
            break
        games_started += 1
        if max_games is not None and games_started >= max_games:
            break
    return {"created": created, "noBet": no_bet, "retryableSkipped": skipped}


def _team_results(row: Any) -> dict[str, dict[str, Any]]:
    away, home = row["away_team"], row["home_team"]
    away_score, home_score = float(row["away_score"]), float(row["home_score"])
    tied = away_score == home_score
    return {
        away: {"won": None if tied else away_score > home_score, "tied": tied, "margin": away_score - home_score, "total": away_score + home_score},
        home: {"won": None if tied else home_score > away_score, "tied": tied, "margin": home_score - away_score, "total": away_score + home_score},
    }


def grade_benchmarks(*, season: int, season_type: str, week: int) -> dict:
    initialize()
    graded, partial = 0, 0
    with get_db_connection() as connection:
        tickets = connection.execute("""SELECT b.*,r.away_team,r.home_team,r.away_score,r.home_score,r.player_stats_json
            FROM nfl_sgp_benchmarks b JOIN nfl_game_result_snapshots r ON r.game_id=b.game_id
            WHERE b.season=? AND b.season_type=? AND b.week=? AND b.ticket_status='PENDING'""",
            (season, season_type, week)).fetchall()
        for ticket in tickets:
            player_stats = json.loads(ticket["player_stats_json"] or "{}")
            team_results = _team_results(ticket)
            leg_rows = connection.execute("SELECT * FROM nfl_sgp_benchmark_legs WHERE benchmark_id=? ORDER BY leg_index", (ticket["id"],)).fetchall()
            results = []
            for leg_row in leg_rows:
                leg = json.loads(leg_row["metadata_json"])
                market = TEAM_MARKET_ALIASES.get(str(leg.get("stat_type") or leg.get("market") or "").upper())
                result = _grade_team_leg(leg, team_results) if market else _grade_player_leg(leg, player_stats)
                results.append(result)
                if result != "pending":
                    connection.execute("UPDATE nfl_sgp_benchmark_legs SET result_status=?,graded_at=? WHERE id=? AND result_status='PENDING'",
                                       (result.upper(), _now(), leg_row["id"]))
            overall = _overall_status(results).upper()
            mapped = {"HIT": "WON", "MISSED": "LOST"}.get(overall, overall)
            if mapped != "PENDING":
                connection.execute("UPDATE nfl_sgp_benchmarks SET ticket_status=?,graded_at=? WHERE id=? AND ticket_status='PENDING'",
                                   (mapped, _now(), ticket["id"]))
                graded += 1
            else:
                partial += 1
            logger.info("nfl_sgp_benchmark_graded %s", _json({"gameId": ticket["game_id"], "profile": ticket["profile"], "result": mapped, "legs": results}))
    return {"graded": graded, "partiallyGraded": partial}


def void_unverifiable_benchmarks(*, season: int, season_type: str, week: int) -> dict:
    """Fail closed while retaining every originally generated leg as evidence."""
    initialize()
    voided = 0
    with get_db_connection() as connection:
        tickets = connection.execute("""SELECT * FROM nfl_sgp_benchmarks
            WHERE season=? AND season_type=? AND week=? AND ticket_status='PENDING'""",
            (season, season_type, week)).fetchall()
        for ticket in tickets:
            legs = connection.execute("SELECT * FROM nfl_sgp_benchmark_legs WHERE benchmark_id=?", (ticket["id"],)).fetchall()
            complete = bool(legs) and all(
                (lambda metadata: metadata.get("provider") == "the-odds-api" and metadata.get("bookmaker")
                 and metadata.get("event_id") and metadata.get("market_timestamp"))
                (json.loads(leg["metadata_json"] or "{}")) for leg in legs
            )
            if complete:
                continue
            at = _now()
            connection.execute("""UPDATE nfl_sgp_benchmarks SET ticket_status='VOID',graded_at=?,
                no_bet_reason='INCOMPLETE_FROZEN_MARKET_PROVENANCE' WHERE id=? AND ticket_status='PENDING'""",
                (at, ticket["id"]))
            connection.execute("UPDATE nfl_sgp_benchmark_legs SET result_status='VOID',graded_at=? WHERE benchmark_id=? AND result_status='PENDING'",
                               (at, ticket["id"]))
            voided += 1
            logger.warning("nfl_sgp_benchmark_voided %s", _json({"gameId": ticket["game_id"], "profile": ticket["profile"], "reason": "INCOMPLETE_FROZEN_MARKET_PROVENANCE"}))
    return {"voided": voided}


def grade_user_parlays(*, season: int, season_type: str, week: int) -> dict:
    """Settle only user tickets carrying genuine, persisted game identities."""
    initialize()
    initialize_parlay_history_database()
    graded, partial, missing_identity = 0, 0, 0
    with get_db_connection() as connection:
        result_rows = connection.execute(
            "SELECT * FROM nfl_game_result_snapshots WHERE season=? AND season_type=? AND week=?",
            (season, season_type, week),
        ).fetchall()
        results = {row["game_id"]: row for row in result_rows}
        rows = connection.execute("""SELECT * FROM parlay_history
            WHERE UPPER(sport)='NFL' AND LOWER(result_status)='pending'
              AND (season=? OR season IS NULL) AND (week=? OR week IS NULL)
            ORDER BY created_at,id""", (season, week)).fetchall()
        for row in rows:
            legs = json.loads(row["legs_json"] or "[]")
            if not legs:
                continue
            leg_results = []
            unresolved_identity = False
            for leg in legs:
                gid = _gid(leg.get("game_id") or row["game_id"]) if (leg.get("game_id") or row["game_id"]) else None
                if not gid:
                    unresolved_identity = True
                    leg_results.append("pending")
                    continue
                final = results.get(gid)
                if not final:
                    leg_results.append("pending")
                    continue
                player_stats = json.loads(final["player_stats_json"] or "{}")
                market = TEAM_MARKET_ALIASES.get(str(leg.get("stat_type") or leg.get("market") or "").upper())
                result = _grade_team_leg(leg, _team_results(final)) if market else _grade_player_leg(leg, player_stats)
                leg["result"] = result.upper()
                leg_results.append(result)
            if unresolved_identity:
                missing_identity += 1
            overall = _overall_status(leg_results).upper()
            status = {"HIT": "WON", "MISSED": "LOST"}.get(overall, overall)
            connection.execute("UPDATE parlay_history SET legs_json=?,result_status=?,settled_at=? WHERE id=?",
                               (_json(legs), status, _now() if status != "PENDING" else None, row["id"]))
            if status == "PENDING":
                partial += 1
            else:
                graded += 1
                logger.info("nfl_user_parlay_settled %s", _json({"parlayId": row["id"], "result": status}))
    return {"graded": graded, "partiallyGraded": partial, "missingGameIdentity": missing_identity}


def prediction_history(*, user_id: int, limit: int = 100) -> list[dict]:
    initialize()
    with get_db_connection() as connection:
        source_rows = connection.execute("""SELECT * FROM nfl_prediction_history
            ORDER BY generated_at DESC,id DESC""").fetchall()
    # Game predictions are published model artifacts, not private customer
    # selections. Show one canonical row per game to every subscriber while
    # keeping customer parlay history user-scoped.
    canonical: dict[str, Any] = {}
    for row in source_rows:
        current = canonical.get(row["game_id"])
        if current is None or (row["user_id"] == 0 and current["user_id"] != 0):
            canonical[row["game_id"]] = row
    rows = sorted(canonical.values(), key=lambda row: (row["generated_at"], row["id"]), reverse=True)[:limit]
    return [{"id": row["prediction_id"], "date": row["generated_at"], "sport": "NFL", "action": "Prediction",
             "gameId": row["game_id"], "matchup": f"{row['away_team']} at {row['home_team']}",
             "predictedWinner": row["predicted_winner"], "modelProbability": row["model_probability"],
             "resultStatus": row["settlement_status"], "awayScore": row["away_score"], "homeScore": row["home_score"],
             "actualWinner": row["actual_winner"], "settledAt": row["settled_at"],
             "summary": f"{row['settlement_status']} — {row['predicted_winner']}", "dataMode": "immutable_pregame_snapshot"}
            for row in rows]


def benchmark_performance(*, season: int, season_type: str, week: int) -> dict:
    initialize()
    with get_db_connection() as connection:
        tickets = [dict(row) for row in connection.execute("SELECT * FROM nfl_sgp_benchmarks WHERE season=? AND season_type=? AND week=?", (season, season_type, week)).fetchall()]
        legs = [dict(row) for row in connection.execute("""SELECT l.*,b.profile FROM nfl_sgp_benchmark_legs l
            JOIN nfl_sgp_benchmarks b ON b.id=l.benchmark_id WHERE b.season=? AND b.season_type=? AND b.week=?""", (season, season_type, week)).fetchall()]
    def ticket_stats(rows: list[dict]) -> dict:
        live = [r for r in rows if r["ticket_status"] != "NO_BET"]
        graded = [r for r in live if r["ticket_status"] in {"WON", "LOST"}]
        ticket_ids = {r["id"] for r in live}
        ticket_legs = [leg for leg in legs if leg["benchmark_id"] in ticket_ids]
        per_ticket = defaultdict(list)
        for leg in ticket_legs:
            per_ticket[leg["benchmark_id"]].append(leg)
        return {"generated": len(rows), "noBet": sum(r["ticket_status"] == "NO_BET" for r in rows),
                "won": sum(r["ticket_status"] == "WON" for r in rows), "lost": sum(r["ticket_status"] == "LOST" for r in rows),
                "pushVoid": sum(r["ticket_status"] in {"PUSH", "VOID"} for r in rows), "pending": sum(r["ticket_status"] == "PENDING" for r in rows),
                "hitRate": round(sum(r["ticket_status"] == "WON" for r in graded) / len(graded) * 100, 1) if graded else None,
                "averageProbability": round(sum(float(r["estimated_probability"]) for r in live if r["estimated_probability"] is not None) / max(1, sum(r["estimated_probability"] is not None for r in live)), 4) if live else None,
                "averageOdds": round(sum(float(r["combined_odds"]) for r in live if r["combined_odds"] is not None) / max(1, sum(r["combined_odds"] is not None for r in live)), 1) if live else None,
                "averageRecommendationScore": round(sum(float(r["recommendation_score"]) for r in live if r["recommendation_score"] is not None) / max(1, sum(r["recommendation_score"] is not None for r in live)), 2) if live else None,
                "averageLegsPerTicket": round(len(ticket_legs) / len(live), 2) if live else None,
                "averageLegsHitPerTicket": round(sum(leg["result_status"] == "HIT" for leg in ticket_legs) / len(live), 2) if live else None,
                "averageLegsMissedPerTicket": round(sum(leg["result_status"] == "MISSED" for leg in ticket_legs) / len(live), 2) if live else None}
    leg_graded = [r for r in legs if r["result_status"] in {"HIT", "MISSED", "PUSH", "VOID"}]
    by_profile = {profile: ticket_stats([r for r in tickets if r["profile"] == profile]) for profile in PROFILES}
    for profile in PROFILES:
        subset = [r for r in legs if r["profile"] == profile]
        done = [r for r in subset if r["result_status"] in {"HIT", "MISSED", "PUSH", "VOID"}]
        by_profile[profile].update({"totalLegs": len(subset), "legsGraded": len(done), "legHitRate": round(sum(r["result_status"] == "HIT" for r in done) / max(1, sum(r["result_status"] in {"HIT", "MISSED"} for r in done)) * 100, 1) if done else None})
    categories = {}
    for market in sorted({r["market_type"] for r in legs}):
        subset = [r for r in legs if r["market_type"] == market]
        decided = [r for r in subset if r["result_status"] in {"HIT", "MISSED"}]
        categories[market] = {"legs": len(subset), "hit": sum(r["result_status"] == "HIT" for r in subset),
                              "missed": sum(r["result_status"] == "MISSED" for r in subset),
                              "pending": sum(r["result_status"] == "PENDING" for r in subset),
                              "hitRate": round(sum(r["result_status"] == "HIT" for r in decided) / len(decided) * 100, 1) if decided else None}
    by_leg_count = {}
    for ticket in tickets:
        count = sum(leg["benchmark_id"] == ticket["id"] for leg in legs)
        key = str(count)
        by_leg_count.setdefault(key, {"tickets": 0, "won": 0, "lost": 0, "pending": 0})
        by_leg_count[key]["tickets"] += 1
        status_key = "won" if ticket["ticket_status"] == "WON" else "lost" if ticket["ticket_status"] == "LOST" else "pending"
        by_leg_count[key][status_key] += 1
    probability_buckets = {}
    for label, low, high in (("<55%", 0, .55), ("55-59.99%", .55, .60), ("60-64.99%", .60, .65), ("65%+", .65, 2)):
        subset = [leg for leg in legs if leg["model_probability"] is not None and low <= float(leg["model_probability"]) < high]
        decided = [leg for leg in subset if leg["result_status"] in {"HIT", "MISSED"}]
        probability_buckets[label] = {"legs": len(subset), "hit": sum(leg["result_status"] == "HIT" for leg in subset),
                                      "missed": sum(leg["result_status"] == "MISSED" for leg in subset),
                                      "hitRate": round(sum(leg["result_status"] == "HIT" for leg in decided) / len(decided) * 100, 1) if decided else None}
    return {"season": season, "seasonType": season_type, "week": week, "overall": ticket_stats(tickets),
            "byProfile": by_profile, "byMarketType": categories, "byLegCount": by_leg_count,
            "byProbabilityBucket": probability_buckets, "totalLegs": len(legs), "legsGraded": len(leg_graded),
            "individualLegHitRate": round(sum(r["result_status"] == "HIT" for r in leg_graded) / max(1, sum(r["result_status"] in {"HIT", "MISSED"} for r in leg_graded)) * 100, 1) if leg_graded else None,
            "sampleStatus": "INSUFFICIENT_SAMPLE" if len(tickets) < 30 else "REPORTABLE"}


def audit_week(*, season: int, season_type: str, week: int, schedule: list[dict] | None = None,
               persist: bool = True) -> dict:
    initialize()
    schedule = schedule if schedule is not None else _schedule(season, week, season_type)
    checks, warnings, critical = [], [], []
    def check(name: str, passed: bool, severity: str = "critical", detail: str | None = None) -> None:
        checks.append({"name": name, "status": "PASS" if passed else "FAIL" if severity == "critical" else "WARN", "detail": detail})
        if not passed:
            (critical if severity == "critical" else warnings).append({"check": name, "detail": detail})
    with get_db_connection() as connection:
        predictions = [dict(r) for r in connection.execute("SELECT * FROM nfl_prediction_history WHERE season=? AND season_type=? AND week=?", (season, season_type, week)).fetchall()]
        source_predictions = {int(r["id"]): dict(r) for r in connection.execute(
            "SELECT id,user_id,game_id,kickoff_time,generated_at,model_version,prediction_json FROM nfl_game_predictions WHERE season=? AND season_type=? AND display_week=?",
            (season, season_type, week),
        ).fetchall()}
        results = [dict(r) for r in connection.execute("SELECT * FROM nfl_game_result_snapshots WHERE season=? AND season_type=? AND week=?", (season, season_type, week)).fetchall()]
        benchmarks = [dict(r) for r in connection.execute("SELECT * FROM nfl_sgp_benchmarks WHERE season=? AND season_type=? AND week=?", (season, season_type, week)).fetchall()]
        benchmark_legs = [dict(r) for r in connection.execute("""SELECT l.*,b.game_id,b.profile,b.ticket_status
            FROM nfl_sgp_benchmark_legs l JOIN nfl_sgp_benchmarks b ON b.id=l.benchmark_id
            WHERE b.season=? AND b.season_type=? AND b.week=?""", (season, season_type, week)).fetchall()]
        provider_attempt = (dict(connection.execute("""SELECT provider,state,attempted_at,completed_at,
            safe_error_code,http_status,market_count,last_market_timestamp FROM nfl_provider_attempts
            WHERE provider='the-odds-api' ORDER BY attempted_at DESC,id DESC LIMIT 1""").fetchone())
            if table_exists(connection, "nfl_provider_attempts") and connection.execute(
                "SELECT COUNT(*) AS count FROM nfl_provider_attempts WHERE provider='the-odds-api'"
            ).fetchone()["count"] else None)
    finals = [g for g in schedule if str(g.get("status") or "").lower() in FINAL]
    game_ids = {_gid(g.get("game_id") or g.get("id")) for g in schedule}
    final_ids = {_gid(g.get("game_id") or g.get("id")) for g in finals}
    result_ids = {r["game_id"] for r in results}
    results_by_game = {r["game_id"]: r for r in results}
    prediction_ids = {p["game_id"] for p in predictions}
    canonical = {}
    for p in predictions:
        canonical.setdefault(p["game_id"], p)
        if p["user_id"] == 0:
            canonical[p["game_id"]] = p
    canonical_predictions = list(canonical.values())
    check("Provider health", bool(schedule), detail=f"{len(schedule)} schedule games")
    odds_healthy = bool(provider_attempt and provider_attempt.get("state") == "HEALTHY")
    check("Odds provider health", odds_healthy, "warning",
          (f"{provider_attempt.get('state')} at {provider_attempt.get('completed_at') or provider_attempt.get('attempted_at')}"
           if provider_attempt else "No persisted provider attempt"))
    check("Schedule integrity", len(game_ids) == len(schedule), detail="canonical game IDs are unique")
    check("Final game ingestion", final_ids <= result_ids, detail=f"{len(final_ids & result_ids)}/{len(final_ids)} finals persisted")
    missing_final_stats = [r for r in results if r["game_id"] in final_ids and not json.loads(r["player_stats_json"] or "{}")]
    check("Final player/team statistics", not missing_final_stats, "warning", f"{len(missing_final_stats)} final games await complete statistics")
    check("Prediction snapshots", game_ids <= prediction_ids, "warning", f"{len(prediction_ids & game_ids)}/{len(game_ids)} games have history")
    altered = [p for p in predictions if p["prediction_id"] not in source_predictions or
               _hash(json.loads(source_predictions[p["prediction_id"]]["prediction_json"])) != p["frozen_prediction_hash"]]
    check("Frozen prediction integrity", not altered, detail=f"{len(altered)} snapshot hashes mismatched")
    post_kickoff = [p for p in predictions if _dt(p["generated_at"]) >= _dt(p["kickoff_time"])]
    check("Pregame timestamp integrity", not post_kickoff, detail=f"{len(post_kickoff)} snapshots generated at/after kickoff")
    unsettled = [p for p in predictions if p["game_id"] in final_ids and p["settlement_status"] == "PENDING"]
    check("Prediction settlement", not unsettled, detail=f"{len(unsettled)} final prediction rows pending")
    incorrect_settlements = []
    for prediction in predictions:
        final = results_by_game.get(prediction["game_id"])
        if not final or prediction["settlement_status"] == "PENDING":
            continue
        tied = final["away_score"] == final["home_score"]
        actual = None if tied else final["home_team"] if final["home_score"] > final["away_score"] else final["away_team"]
        expected = "PUSH" if tied else "WON" if prediction["predicted_winner"] == actual else "LOST"
        if prediction["settlement_status"] != expected or prediction["away_score"] != final["away_score"] or prediction["home_score"] != final["home_score"]:
            incorrect_settlements.append(prediction["prediction_id"])
    check("Settlement result integrity", not incorrect_settlements, detail=f"{len(incorrect_settlements)} settled rows disagree with provider finals")
    duplicate_canonical = len(predictions) != len({p["prediction_id"] for p in predictions})
    check("History synchronization", not duplicate_canonical, detail="prediction IDs are unique")
    for profile in PROFILES:
        covered = {b["game_id"] for b in benchmarks if b["profile"] == profile}
        eligible = {_gid(g.get("game_id") or g.get("id")) for g in schedule if _dt(g.get("kickoff_time") or g.get("startTimeUtc")) > datetime.now(timezone.utc)}
        check(f"SGP {profile} coverage", eligible <= covered, "warning", f"{len(covered & game_ids)}/{len(game_ids)} games recorded; future eligible {len(eligible)}")
    pending_final = [b for b in benchmarks if b["game_id"] in final_ids and b["ticket_status"] == "PENDING"]
    check("SGP grading", not pending_final, "warning", f"{len(pending_final)} final tickets pending provider stats")
    invalid_benchmark_times = [b for b in benchmarks if _dt(b["generated_at"]) >= _dt(b["kickoff_time"])]
    check("SGP pregame integrity", not invalid_benchmark_times, detail=f"{len(invalid_benchmark_times)} tickets generated at/after kickoff")
    invalid_market_provenance = []
    for leg in benchmark_legs:
        metadata = json.loads(leg["metadata_json"] or "{}")
        if leg["ticket_status"] != "NO_BET" and not (
            metadata.get("provider") == "the-odds-api" and metadata.get("bookmaker")
            and metadata.get("event_id") and metadata.get("market_timestamp")
        ):
            invalid_market_provenance.append(leg["id"])
    check("SGP market provenance", not invalid_market_provenance, "warning",
          f"{len(invalid_market_provenance)} legs lack complete frozen provider provenance")
    performance = benchmark_performance(season=season, season_type=season_type, week=week)
    check("Performance aggregation", True, detail=f"{performance['overall']['generated']} benchmark rows")
    root = Path(__file__).resolve().parents[3]
    frontend_paths = [root / "frontend" / "app" / name / "page.jsx" for name in
                      ("dashboard", "games", "analyze", "parlays", "history", "performance", "internal/operations")]
    check("Frontend smoke tests", all(path.exists() for path in frontend_paths), detail=f"{sum(path.exists() for path in frontend_paths)}/{len(frontend_paths)} critical route modules present")
    counts = {"scheduledGames": len(schedule), "finalGames": len(finals),
              "finalPredictionsGraded": sum(p["game_id"] in final_ids and p["settlement_status"] != "PENDING" for p in canonical_predictions),
              "correctPredictions": sum(p["settlement_status"] == "WON" for p in canonical_predictions),
              "incorrectPredictions": sum(p["settlement_status"] == "LOST" for p in canonical_predictions),
              "benchmarkSgps": len(benchmarks), "sgpsGraded": sum(b["ticket_status"] in {"WON", "LOST", "PUSH", "VOID"} for b in benchmarks),
              "sgpsPending": sum(b["ticket_status"] == "PENDING" for b in benchmarks), "noBet": sum(b["ticket_status"] == "NO_BET" for b in benchmarks)}
    result = "PASS" if not critical else "FAIL"
    report = {"title": f"SMARTBETSPORTS — NFL {season} {season_type.upper()} WEEK {week} PRODUCTION AUDIT",
              "auditId": str(uuid4()), "league": "NFL", "season": season, "seasonType": season_type, "week": week,
              "createdAt": _now(), "result": result, "checks": checks, "counts": counts,
              "criticalErrors": critical, "warnings": warnings, "performance": performance,
              "providerHealth": {"schedule": "HEALTHY" if schedule else "UNAVAILABLE",
                                 "odds": provider_attempt or {"state": "UNKNOWN"}}}
    # Keep operational output portable across Windows consoles and log collectors.
    report["title"] = f"SMARTBETSPORTS - NFL {season} {season_type.upper()} WEEK {week} PRODUCTION AUDIT"
    if persist:
        with get_db_connection() as connection:
            connection.execute("""INSERT INTO nfl_production_audits
                (audit_id,league,season,season_type,week,result,critical_errors,warnings,report_json,created_at)
                VALUES (?,?,?,?,?,?,?,?,?,?)""", (report["auditId"], "NFL", season, season_type, week, result, len(critical), len(warnings), _json(report), report["createdAt"]))
    logger.info("nfl_production_audit %s", _json({"season": season, "seasonType": season_type, "week": week, "result": result, "critical": len(critical), "warnings": len(warnings)}))
    return report


def latest_audit(*, season: int, season_type: str, week: int) -> dict | None:
    initialize()
    with get_db_connection() as connection:
        row = connection.execute("SELECT report_json FROM nfl_production_audits WHERE season=? AND season_type=? AND week=? ORDER BY created_at DESC,id DESC LIMIT 1", (season, season_type, week)).fetchone()
    return json.loads(row["report_json"]) if row else None


def run_lifecycle(*, season: int, season_type: str, week: int, generate: bool = True,
                  max_benchmark_games: int = 1) -> dict:
    schedule = _schedule(season, week, season_type)
    history = capture_prediction_history(season=season, season_type=season_type, week=week, schedule=schedule)
    new_results, provider_errors = 0, []
    initialize()
    with get_db_connection() as connection:
        complete_result_ids = {
            row["game_id"] for row in connection.execute(
                "SELECT game_id,player_stats_json FROM nfl_game_result_snapshots WHERE season=? AND season_type=? AND week=?",
                (season, season_type, week),
            ).fetchall() if json.loads(row["player_stats_json"] or "{}")
        }
    for game in schedule:
        if str(game.get("status") or "").lower() not in FINAL:
            continue
        if _gid(game.get("game_id") or game.get("id")) in complete_result_ids:
            continue
        try:
            detail = get_nfl_game_detail(str(game.get("game_id") or game.get("id")), force=True, trigger="production_lifecycle")
            new_results += int(persist_final(detail))
        except Exception as exc:
            provider_errors.append({"gameId": _gid(game.get("game_id") or game.get("id")), "error": type(exc).__name__})
            logger.exception("nfl_final_ingestion_failed", extra={"game_id": game.get("game_id") or game.get("id")})
    settlement = settle_predictions(season=season, season_type=season_type, week=week)
    benchmarks = generate_benchmarks(season=season, season_type=season_type, week=week, schedule=schedule,
                                     max_games=max_benchmark_games, max_tickets=1) if generate else {"created": 0, "noBet": 0, "retryableSkipped": 0}
    integrity = void_unverifiable_benchmarks(season=season, season_type=season_type, week=week)
    grading = grade_benchmarks(season=season, season_type=season_type, week=week)
    user_grading = grade_user_parlays(season=season, season_type=season_type, week=week)
    audit = audit_week(season=season, season_type=season_type, week=week, schedule=schedule)
    return {"history": history, "newFinalResults": new_results, "predictionSettlement": settlement,
            "benchmarks": benchmarks, "benchmarkIntegrity": integrity, "benchmarkGrading": grading, "userParlayGrading": user_grading,
            "providerErrors": provider_errors, "audit": audit}
