"""Small, owner-visible audit trail for operational actions."""
from __future__ import annotations

from datetime import datetime, timezone
import json
import uuid

from backend.app.database import get_db_connection, using_postgres


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def initialize() -> None:
    identifier = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if using_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"
    with get_db_connection() as connection:
        connection.execute(f"""CREATE TABLE IF NOT EXISTS operator_actions (
            id {identifier}, action_id TEXT NOT NULL UNIQUE, action TEXT NOT NULL,
            actor TEXT NOT NULL, target TEXT NOT NULL, started_at TEXT NOT NULL,
            completed_at TEXT, result TEXT NOT NULL, error TEXT, artifact TEXT,
            status_change TEXT, metadata_json TEXT NOT NULL
        )""")
        connection.execute("CREATE INDEX IF NOT EXISTS idx_operator_actions_started ON operator_actions(started_at)")
        if using_postgres():
            # Operational audit entries are available only to the backend's
            # direct database role, never to browser-facing Data API roles.
            connection.execute("ALTER TABLE operator_actions ENABLE ROW LEVEL SECURITY")
            connection.execute("REVOKE ALL ON TABLE operator_actions FROM anon, authenticated")


def start(action: str, actor: str, target: str, metadata: dict | None = None) -> str:
    initialize()
    action_id = str(uuid.uuid4())
    with get_db_connection() as connection:
        connection.execute(
            "INSERT INTO operator_actions(action_id,action,actor,target,started_at,result,metadata_json) VALUES(?,?,?,?,?,'RUNNING',?)",
            (action_id, action, actor, target, _now(), json.dumps(metadata or {}, sort_keys=True)),
        )
    return action_id


def finish(action_id: str, *, result: str, error: str | None = None,
           artifact: str | None = None, status_change: str | None = None) -> None:
    with get_db_connection() as connection:
        connection.execute(
            "UPDATE operator_actions SET completed_at=?,result=?,error=?,artifact=?,status_change=? WHERE action_id=?",
            (_now(), result, error, artifact, status_change, action_id),
        )


def recent(limit: int = 30) -> list[dict]:
    initialize()
    with get_db_connection() as connection:
        rows = connection.execute(
            "SELECT action_id,action,actor,target,started_at,completed_at,result,error,artifact,status_change "
            "FROM operator_actions ORDER BY started_at DESC LIMIT ?", (max(1, min(limit, 100)),),
        ).fetchall()
    return [dict(row) for row in rows]
