"""Production-safe parlay history storage for the web API."""

from __future__ import annotations

import json

from backend.app.database import column_exists, get_db_connection, using_postgres


def initialize_parlay_history_database() -> None:
    identifier = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if using_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"
    with get_db_connection() as connection:
        connection.execute(f"""
            CREATE TABLE IF NOT EXISTS parlay_history (
                id {identifier},
                user_id BIGINT,
                sport TEXT NOT NULL,
                created_at TEXT NOT NULL,
                difficulty TEXT NOT NULL,
                legs_json TEXT NOT NULL,
                estimated_odds INTEGER,
                combined_probability REAL,
                result_status TEXT NOT NULL DEFAULT 'pending',
                notes TEXT,
                model_version TEXT
            )
        """)
        if not column_exists(connection, "parlay_history", "user_id"):
            connection.execute("ALTER TABLE parlay_history ADD COLUMN user_id BIGINT")
        if not column_exists(connection, "parlay_history", "model_version"):
            connection.execute("ALTER TABLE parlay_history ADD COLUMN model_version TEXT")
        additions = {
            "game_id": "TEXT", "season": "INTEGER", "season_type": "TEXT", "week": "INTEGER",
            "kickoff_time": "TEXT", "settled_at": "TEXT", "source_type": "TEXT DEFAULT 'USER'",
            "game_ids_json": "TEXT",
        }
        for column, definition in additions.items():
            if not column_exists(connection, "parlay_history", column):
                connection.execute(f"ALTER TABLE parlay_history ADD COLUMN {column} {definition}")
        connection.execute(
            "CREATE INDEX IF NOT EXISTS idx_parlay_history_user_created ON parlay_history(user_id, created_at)"
        )


def _legs(parlay_result) -> list[dict]:
    return [
        {
            "sport": getattr(leg.sport, "value", leg.sport),
            "player": leg.player,
            "team": leg.team,
            "stat_type": leg.stat_type,
            "line": leg.line,
            "odds": leg.odds,
            "prediction": leg.prediction,
            "confidence": leg.confidence,
            "notes": leg.notes,
            "provider": getattr(leg, "provider", None),
            "bookmaker": getattr(leg, "bookmaker", None),
            "event_id": getattr(leg, "event_id", None),
            "market_timestamp": getattr(leg, "market_timestamp", None),
            "market_kickoff": getattr(leg, "market_kickoff", None),
        }
        for leg in parlay_result.parlay.legs
    ]


def save_web_parlay(parlay_result, *, user_id: int, model_version: str,
                    context: dict | None = None) -> int:
    initialize_parlay_history_database()
    parlay = parlay_result.parlay
    context = context or {}
    legs = _legs(parlay_result)
    leg_games = context.get("legGameIds") or {}
    for leg in legs:
        game_id = leg_games.get(str(leg.get("team") or "").upper()) or context.get("gameId")
        if game_id:
            leg["game_id"] = game_id
    with get_db_connection() as connection:
        inserted = connection.execute(
            """
            INSERT INTO parlay_history (
                user_id, sport, created_at, difficulty, legs_json,
                estimated_odds, combined_probability, result_status, notes,
                model_version, game_id, season, season_type, week, kickoff_time,
                source_type, game_ids_json
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
            """,
            (
                user_id,
                getattr(parlay.sport, "value", parlay.sport),
                parlay.created_at,
                getattr(parlay.difficulty, "value", parlay.difficulty),
                json.dumps(legs),
                parlay_result.estimated_odds,
                parlay_result.combined_probability,
                parlay_result.result_status,
                parlay_result.notes or parlay.notes,
                model_version,
                context.get("gameId"),
                context.get("season"),
                context.get("seasonType"),
                context.get("week"),
                context.get("kickoffTime"),
                "USER",
                json.dumps(sorted(set(leg_games.values()))) if leg_games else None,
            ),
        ).fetchone()
    return int(inserted["id"])


def load_web_parlays(*, user_id: int | None = None, sport: str | None = None,
                     difficulty: str | None = None, limit: int = 100) -> list[dict]:
    initialize_parlay_history_database()
    filters: list[str] = []
    params: list[object] = []
    if user_id is not None:
        filters.append("user_id=?")
        params.append(user_id)
    if sport:
        filters.append("UPPER(sport)=?")
        params.append(str(sport).upper())
    if difficulty:
        filters.append("UPPER(difficulty)=?")
        params.append(str(difficulty).upper())
    where = f"WHERE {' AND '.join(filters)}" if filters else ""
    params.append(max(1, min(int(limit), 500)))
    with get_db_connection() as connection:
        rows = connection.execute(
            f"SELECT * FROM parlay_history {where} ORDER BY created_at DESC, id DESC LIMIT ?",
            params,
        ).fetchall()
    return [dict(row) for row in rows]
