'use client';

import {useEffect,useMemo,useState} from 'react';
import SubscriptionGuard from '@/components/auth/SubscriptionGuard';
import RiskLevelSelector from '@/components/analyze/RiskLevelSelector';
import GlowCard from '@/components/ui/GlowCard';
import NflMatchup from '@/components/games/NflMatchup';
import {api} from '@/lib/api';

const MODES=[['winners','Game Winners','Inspect every matchup or optionally select moneyline winners.'],['same_game','Same Game Parlay','Choose one matchup, then generate team and player selections.'],['multi_game','Multi-Game Parlay','Combine selections from games across the week.']];
const DAYS=['ALL','THURSDAY','SUNDAY','MONDAY'];

export default function Parlays(){return <SubscriptionGuard><Builder/></SubscriptionGuard>}
function Builder(){
  const[mode,setMode]=useState('winners'),[profile,setProfile]=useState('BALANCED'),[week,setWeek]=useState(1),[day,setDay]=useState('ALL');
  const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[picks,setPicks]=useState({}),[result,setResult]=useState(null),[selectedGame,setSelectedGame]=useState(null);
  useEffect(()=>{const query=new URLSearchParams(window.location.search);const requestedMode=query.get('mode');const requestedDay=query.get('day');if(MODES.some(([id])=>id===requestedMode))setMode(requestedMode);if(DAYS.includes(requestedDay))setDay(requestedDay)},[]);
  useEffect(()=>{setLoading(true);setError('');api.nfl.week({week,profile,day}).then(board=>{setData(board);setPicks(current=>Object.fromEntries(Object.entries(current).filter(([id])=>board.items.some(game=>game.game_id===id))));setSelectedGame(current=>current&&board.items.some(game=>game.game_id===current.game_id)?current:null)}).catch(exc=>setError(exc.message)).finally(()=>setLoading(false))},[week,profile,day]);
  const games=data?.items||[];
  const selections=useMemo(()=>games.flatMap(game=>picks[game.game_id]?[{game,team:picks[game.game_id],odds:picks[game.game_id]===game.home_team?game.market.homeOdds:game.market.awayOdds}]:[]),[games,picks]);
  function switchMode(value){setMode(value);setSelectedGame(null);setResult(null)}
  function choose(game,team){setPicks(current=>({...current,[game.game_id]:current[game.game_id]===team?undefined:team}))}
  function recommended(){setPicks(Object.fromEntries(games.filter(game=>game.recommended&&game.winner).map(game=>[game.game_id,game.winner])))}
  async function generateSameGame(){if(!selectedGame)return;setResult(null);setError('');try{setResult(await api.nfl.parlay({mode:'same_game',difficulty:profile,homeTeam:selectedGame.home_team,awayTeam:selectedGame.away_team}))}catch(exc){setError(exc.message)}}
  return <main className="mx-auto min-h-screen max-w-7xl px-4 pb-28 pt-10 sm:px-6 md:pt-14">
    <p className="text-sm font-bold uppercase tracking-[.22em] text-cyan-300">NFL week center</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] md:text-6xl">Build from the games first.</h1><p className="mt-3 max-w-3xl text-slate-300">Every scheduled game stays visible. Selecting winners and creating a parlay are always optional.</p>
    <div className="mt-7 grid gap-3 md:grid-cols-3">{MODES.map(([id,title,copy])=><button key={id} aria-pressed={mode===id} onClick={()=>switchMode(id)} className={`rounded-3xl border p-5 text-left transition hover:-translate-y-1 focus:outline focus:outline-2 focus:outline-cyan-300 ${mode===id?'border-cyan-300 bg-cyan-300/15':'border-white/10 bg-white/5 hover:bg-white/10'}`}><b className="text-xl">{title}</b><span className="mt-1 block text-sm text-slate-300">{copy}</span></button>)}</div>
    <GlowCard className="mt-5 p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><label className="text-sm font-semibold text-slate-300">Regular-season week</label><div className="mt-2 flex items-center gap-2"><button className="btn btn-glass" disabled={week===1} onClick={()=>setWeek(value=>value-1)}>Previous</button><strong className="min-w-24 text-center text-xl">Week {week}</strong><button className="btn btn-glass" disabled={week===18} onClick={()=>setWeek(value=>value+1)}>Next</button></div></div><div className="flex flex-wrap gap-2">{DAYS.map(value=><button key={value} onClick={()=>setDay(value)} className={`rounded-full px-4 py-2 text-sm font-bold ${day===value?'bg-cyan-300 text-slate-950':'bg-white/10 text-slate-200'}`}>{value==='ALL'?'All days':value[0]+value.slice(1).toLowerCase()}</button>)}</div></div></GlowCard>
    {error&&<GlowCard className="mt-5 border-red-400/40 p-5 text-red-100"><b>Unable to load verified data.</b><p className="mt-1">{error}</p></GlowCard>}
    {loading?<LoadingCards/>:games.length?<div className="mt-5 grid gap-4 lg:grid-cols-[1fr_350px]"><section className="grid content-start gap-4 md:grid-cols-2">{games.map(game=><GameCard key={game.game_id} game={game} mode={mode} picked={picks[game.game_id]} selected={selectedGame?.game_id===game.game_id} choose={choose} selectGame={setSelectedGame}/>)}</section><aside className="lg:sticky lg:top-24 lg:self-start"><SelectionPanel mode={mode} profile={profile} setProfile={setProfile} selectedGame={selectedGame} selections={selections} recommended={recommended} generateSameGame={generateSameGame}/>{result&&<SameGameResult result={result}/>}</aside></div>:!error&&<GlowCard className="mt-5 p-8 text-center text-slate-300">No games match this week and day filter.</GlowCard>}
  </main>
}

function LoadingCards(){return <div className="mt-5 grid gap-4 md:grid-cols-2">{[1,2,3,4].map(value=><div key={value} className="h-64 animate-pulse rounded-3xl bg-white/10"/>)}</div>}
function SelectionPanel({mode,profile,setProfile,selectedGame,selections,recommended,generateSameGame}){if(mode==='same_game')return <GlowCard className="p-5"><h2 className="text-xl font-black">Same-game setup</h2>{selectedGame?<><p className="mt-2 rounded-2xl bg-cyan-300/10 p-3 font-bold">{selectedGame.away_team} at {selectedGame.home_team}</p><div className="mt-4"><p className="mb-2 text-sm font-bold text-slate-300">Choose risk profile</p><RiskLevelSelector value={profile} onChange={setProfile}/></div><button className="btn btn-primary mt-4 w-full" onClick={generateSameGame}>Run same-game analysis</button></>:<p className="mt-3 text-sm text-slate-400">Choose one matchup from the weekly board. Risk profile comes next.</p>}</GlowCard>;return <GlowCard className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-black">{mode==='winners'?'Optional winner selections':'Multi-game selections'}</h2><button className="text-sm text-cyan-200" onClick={recommended}>Use recommendations</button></div>{selections.length?<div className="mt-4 grid gap-3">{selections.map(({game,team,odds})=><div className="rounded-2xl bg-white/5 p-3" key={game.game_id}><b>{team} moneyline</b><p className="text-sm text-slate-400">{game.away_team} at {game.home_team} · {odds==null?'Odds unavailable':odds>0?`+${odds}`:odds}</p></div>)}</div>:<p className="mt-4 text-sm text-slate-400">Select at most one winner per game. You can inspect the entire board without making a selection.</p>}{mode==='multi_game'&&<div className="mt-5 border-t border-white/10 pt-4"><p className="mb-2 text-sm font-bold text-slate-300">Choose risk profile after selecting games</p><RiskLevelSelector value={profile} onChange={setProfile}/></div>}<p className="mt-4 border-t border-white/10 pt-4 text-xs text-slate-500">PASS is valid whenever the price or model edge is unavailable.</p></GlowCard>}
function SameGameResult({result}){return <GlowCard className="mt-4 p-5"><h2 className="font-black">Same-game result</h2>{result.legs?.length?<div className="mt-3 grid gap-2">{result.legs.map((leg,index)=><p key={`${leg.prediction}-${index}`} className="rounded-xl bg-white/5 p-3 text-sm">{leg.prediction} · {leg.odds>0?'+':''}{leg.odds}</p>)}</div>:<p className="mt-2 text-sm text-slate-300">No verified live props met this profile. No sample legs were substituted.</p>}{result.correlationWarning&&<p className="mt-3 text-xs text-amber-200">{result.correlationWarning}</p>}</GlowCard>}
function GameCard({game,mode,picked,selected,choose,selectGame}){const kickoff=new Date(game.kickoff_time);return <article className={`flex min-h-[430px] flex-col rounded-3xl border p-5 ${selected?'border-cyan-300 bg-cyan-300/10':'border-white/10 bg-white/[.04]'}`}><div className="flex min-h-8 items-center justify-between gap-3"><span className="tag">{new Intl.DateTimeFormat(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'}).format(kickoff)}</span>{game.recommended?<span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-200">Recommended</span>:<span className="text-xs text-slate-500">Available to inspect</span>}</div><NflMatchup game={game} size={46} className="mt-5"/><p className="mt-3 text-center text-sm text-slate-400">{game.venue||'Venue TBD'}</p>{game.predictionStatus==='available'?<div className="mt-4 rounded-2xl bg-cyan-300/10 p-4"><p className="text-sm text-slate-300">SmartBetSports model pick</p><p className="mt-1 text-2xl font-black text-cyan-100">{game.winner} · {(game.winProbability*100).toFixed(1)}%</p><p className="mt-2 text-xs leading-relaxed text-slate-400">Model confidence {game.confidence}% · projected {game.away_team} {game.projectedAwayScore} – {game.home_team} {game.projectedHomeScore}{game.edge==null?' · market edge unavailable':` · edge ${(game.edge*100).toFixed(1)} pts`}</p></div>:<p className="mt-4 rounded-2xl bg-white/5 p-4 text-sm text-slate-300">Prediction unavailable. The matchup remains visible; no estimate was invented.</p>}<div className="mt-auto pt-4">{mode==='same_game'?<button disabled={game.predictionStatus!=='available'} onClick={()=>selectGame(game)} className="btn btn-primary w-full">{selected?'Selected matchup':'Choose this matchup'}</button>:<div className="grid grid-cols-2 gap-2">{[[game.away_team,game.market.awayOdds],[game.home_team,game.market.homeOdds]].map(([team,odds])=><button key={team} aria-pressed={picked===team} onClick={()=>choose(game,team)} className={`rounded-2xl border p-3 font-bold ${picked===team?'border-cyan-300 bg-cyan-300/20':'border-white/10 bg-white/5'}`}>{team}<span className="block text-xs font-normal text-slate-400">{odds==null?'Price unavailable':odds>0?`+${odds}`:odds}</span></button>)}</div>}</div></article>}
