'use client';
import Link from 'next/link';
import {useParams,useSearchParams} from 'next/navigation';
import {useEffect,useState} from 'react';
import SubscriptionGuard from '@/components/auth/SubscriptionGuard';
import GlowCard from '@/components/ui/GlowCard';
import NflMatchup from '@/components/games/NflMatchup';
import {api} from '@/lib/api';
export default function Game(){return <SubscriptionGuard><Detail/></SubscriptionGuard>}
function Detail(){const{slug}=useParams();const search=useSearchParams();const week=Number(search.get('week')||1);const[game,setGame]=useState(null),[done,setDone]=useState(false);useEffect(()=>{api.nfl.week({week}).then(data=>setGame(data.items.find(row=>row.game_id===slug)||null)).finally(()=>setDone(true))},[slug,week]);if(!done)return <main className="mx-auto max-w-4xl px-6 pt-16"><div className="h-80 animate-pulse rounded-3xl bg-white/10"/></main>;return <main className="mx-auto min-h-screen max-w-4xl px-6 pb-24 pt-12"><Link href="/games" className="text-cyan-200">← Back to weekly games</Link>{!game?<GlowCard className="mt-6 p-8">This game is not available in the selected week.</GlowCard>:<><p className="mt-8 text-sm text-slate-400">Week {week} · {new Date(game.kickoff_time).toLocaleString()}</p><h1 className="sr-only">{game.away_team} at {game.home_team}</h1><GlowCard className="mt-4 p-6 sm:p-8"><NflMatchup game={game} size={64}/><p className="mt-5 text-center text-slate-400">{game.venue||'Venue TBD'}{game.broadcast?.length?` · ${game.broadcast.join(', ')}`:''}</p></GlowCard><div className="mt-5 grid gap-4 sm:grid-cols-2"><GlowCard className="p-6"><p className="text-sm text-slate-400">Model winner</p><p className="mt-2 text-4xl font-black text-cyan-100">{game.winner||'Unavailable'}</p>{game.winProbability&&<p className="mt-2">{(game.winProbability*100).toFixed(1)}% model win probability</p>}</GlowCard><GlowCard className="p-6"><p className="text-sm text-slate-400">Score projection</p><p className="mt-2 text-2xl font-black">{game.away_team} {game.projectedAwayScore??'—'}</p><p className="text-2xl font-black">{game.home_team} {game.projectedHomeScore??'—'}</p></GlowCard></div><GlowCard className="mt-4 p-6"><h2 className="text-xl font-black">Market context</h2><p className="mt-2 text-slate-300">{game.market.sportsbook?`${game.market.sportsbook}: ${game.away_team} ${game.market.awayOdds>0?'+':''}${game.market.awayOdds}, ${game.home_team} ${game.market.homeOdds>0?'+':''}${game.market.homeOdds}`:'No verified live moneyline is attached. The model projection remains visible without an invented price.'}</p><p className="mt-3 text-sm text-slate-500">Model {game.modelVersion} · data through {game.dataAsOf||'unavailable'}</p></GlowCard></>}</main>}
