'use client';

import {useEffect,useMemo,useState} from 'react';
import SubscriptionGuard from '@/components/auth/SubscriptionGuard';
import GlowCard from '@/components/ui/GlowCard';
import {api} from '@/lib/api';

const OFFENSE=['QB','RB','WR1','WR2','WR3','TE','LT','LG','C','RG','RT','FLEX'];
const DEFENSE=['EDGE1','DT1','DT2','EDGE2','LB1','LB2','CB1','CB2','S1','S2'];
const POSITION={QB:['QB'],RB:['RB'],WR1:['WR'],WR2:['WR'],WR3:['WR'],TE:['TE'],LT:['OT','T'],LG:['G','OG'],C:['C'],RG:['G','OG'],RT:['OT','T'],FLEX:['RB','WR','TE'],EDGE1:['DE','EDGE'],EDGE2:['DE','EDGE'],DT1:['DT','NT'],DT2:['DT','NT'],LB1:['LB','ILB','OLB'],LB2:['LB','ILB','OLB'],CB1:['CB'],CB2:['CB'],S1:['S','FS','SS'],S2:['S','FS','SS']};

export default function Fantasy(){return <SubscriptionGuard><DepthChart/></SubscriptionGuard>}
function DepthChart(){
  const[data,setData]=useState(null),[formation,setFormation]=useState({}),[activeSlot,setActiveSlot]=useState('QB'),[query,setQuery]=useState(''),[name,setName]=useState('My 2026 Team'),[chartId,setChartId]=useState(null),[message,setMessage]=useState(''),[error,setError]=useState('');
  const load=()=>api.nfl.depthCharts().then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
  const byId=useMemo(()=>Object.fromEntries((data?.players||[]).map(p=>[p.id,p])),[data]);
  const candidates=useMemo(()=>{const allowed=POSITION[activeSlot]||[];return(data?.players||[]).filter(p=>allowed.includes(p.position)&&(!query||p.player.toLowerCase().includes(query.toLowerCase())||p.team.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>(a.fantasy?.rank||9999)-(b.fantasy?.rank||9999)||a.player.localeCompare(b.player)).slice(0,60)},[data,activeSlot,query]);
  async function save(){setError('');try{const row=chartId?await api.nfl.updateDepthChart(chartId,{name,formation}):await api.nfl.saveDepthChart({name,formation});setChartId(row.id);setMessage('Depth chart saved.');await load()}catch(e){setError(e.message)}}
  function edit(row){setChartId(row.id);setName(row.name);setFormation(row.formation||{});setMessage(`Editing ${row.name}`)}
  async function remove(id){try{await api.nfl.deleteDepthChart(id);if(chartId===id){setChartId(null);setFormation({})}await load()}catch(e){setError(e.message)}}
  return <main className="mx-auto min-h-screen max-w-7xl px-4 pb-28 pt-10 sm:px-6 md:pt-14"><p className="text-sm font-bold uppercase tracking-[.22em] text-cyan-300">Fantasy command center</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] md:text-6xl">Build your depth chart.</h1><p className="mt-3 max-w-3xl text-slate-300">Real 2026 roster identities fill every position. Fantasy skill players include model scores anchored to complete 2025 game production; positions without a defensible fantasy projection show roster facts only.</p>
    {error&&<p className="mt-5 rounded-2xl bg-red-500/15 p-4 text-red-100">{error}</p>}{!data?<div className="mt-6 h-96 animate-pulse rounded-3xl bg-white/10"/>:<div className="mt-6 grid gap-5 xl:grid-cols-[1fr_380px]"><section><div className="rounded-[2rem] border border-emerald-300/20 bg-gradient-to-b from-emerald-950/90 to-emerald-900/40 p-4 shadow-2xl"><div className="grid gap-3 sm:grid-cols-2"><Unit title="Offense" slots={OFFENSE} active={activeSlot} setActive={setActiveSlot} formation={formation} byId={byId}/><Unit title="Defense" slots={DEFENSE} active={activeSlot} setActive={setActiveSlot} formation={formation} byId={byId}/></div></div><GlowCard className="mt-4 p-5"><h2 className="text-xl font-black">Save this lineup</h2><div className="mt-3 flex flex-wrap gap-3"><input aria-label="Depth chart name" value={name} onChange={e=>setName(e.target.value)} className="min-w-60 flex-1 rounded-xl border border-white/10 bg-white/5 px-4 py-3"/><button className="btn btn-primary" onClick={save}>{chartId?'Update':'Save'} chart</button><button className="btn btn-glass" onClick={()=>{setChartId(null);setFormation({});setName('My 2026 Team')}}>New</button></div>{message&&<p className="mt-3 text-sm text-cyan-200">{message}</p>}{data.savedCharts?.length>0&&<div className="mt-4 grid gap-2">{data.savedCharts.map(row=><div key={row.id} className="flex items-center justify-between rounded-xl bg-white/5 p-3"><button className="text-left font-bold" onClick={()=>edit(row)}>{row.name}<span className="block text-xs font-normal text-slate-500">Updated {new Date(row.updatedAt).toLocaleString()}</span></button><button className="text-sm text-red-200" onClick={()=>remove(row.id)}>Delete</button></div>)}</div>}</GlowCard></section>
      <aside className="xl:sticky xl:top-24 xl:self-start"><GlowCard className="p-5"><h2 className="text-2xl font-black">Choose {activeSlot}</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search player or team" className="mt-3 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3"/><div className="mt-4 max-h-[65vh] space-y-2 overflow-y-auto pr-1">{candidates.length?candidates.map(player=><button key={player.id} onClick={()=>setFormation(current=>({...current,[activeSlot]:player.id}))} className="w-full rounded-2xl border border-white/10 bg-white/5 p-3 text-left hover:border-cyan-300/50"><div className="flex justify-between gap-3"><b>{player.player}</b><span className="text-sm text-slate-400">{player.team} · {player.position}</span></div>{player.fantasy?<p className="mt-1 text-xs text-cyan-100">#{player.fantasy.rank} overall · {player.fantasy.projectedFantasyPoints} projected pts · {player.fantasy.tier}</p>:<p className="mt-1 text-xs text-slate-500">Active roster identity · no fantasy score claimed</p>}</button>):<p className="text-sm text-slate-400">No verified roster players match this slot and search.</p>}</div></GlowCard></aside></div>}
  </main>
}
function Unit({title,slots,active,setActive,formation,byId}){return <div><h2 className="mb-3 text-center text-xl font-black uppercase tracking-widest text-white/80">{title}</h2><div className="grid grid-cols-2 gap-2">{slots.map(slot=>{const player=byId[formation[slot]];return <button key={slot} aria-pressed={active===slot} onClick={()=>setActive(slot)} className={`min-h-20 rounded-2xl border p-3 text-left ${active===slot?'border-cyan-200 bg-cyan-200/20':'border-white/15 bg-black/25'}`}><span className="text-xs font-black text-emerald-200">{slot}</span><span className="mt-1 block truncate font-bold">{player?.player||'Open slot'}</span><span className="block text-xs text-white/50">{player?`${player.team} · ${player.position}`:'Tap to fill'}</span></button>})}</div></div>}
