'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import SubscriptionGuard from '@/components/auth/SubscriptionGuard';
import GlowCard from '@/components/ui/GlowCard';
import NflMatchup from '@/components/games/NflMatchup';
import {api} from '@/lib/api';
export default function Games(){return <SubscriptionGuard><Board/></SubscriptionGuard>}
function Board(){const[week,setWeek]=useState(1),[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{setData(null);setError('');api.nfl.week({week}).then(setData).catch(e=>setError(e.message))},[week]);return <main className="mx-auto min-h-screen max-w-6xl px-4 pb-24 pt-10 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-300">NFL schedule</p><h1 className="mt-2 text-5xl font-black tracking-[-.06em]">Week {week}</h1></div><div className="flex flex-wrap gap-2"><button className="btn btn-glass" disabled={week===1} onClick={()=>setWeek(w=>w-1)}>Previous</button><button className="btn btn-glass" disabled={week===18} onClick={()=>setWeek(w=>w+1)}>Next</button><Link href="/parlays" className="btn btn-primary">Build picks</Link></div></div>{error&&<GlowCard className="mt-6 p-5 text-red-100">{error}</GlowCard>}{!data&&!error?<div className="mt-6 h-80 animate-pulse rounded-3xl bg-white/10"/>:<div className="mt-7 grid gap-5 md:grid-cols-2">{data?.items?.map(game=><Link href={`/games/${game.game_id}?week=${week}`} key={game.game_id} className="flex min-h-56 flex-col rounded-3xl border border-white/10 bg-white/5 p-6 transition hover:-translate-y-0.5 hover:border-cyan-300/50"><p className="text-sm text-slate-400">{new Date(game.kickoff_time).toLocaleString()}</p><NflMatchup game={game} size={50} className="mt-5"/><div className="mt-auto flex flex-wrap items-end justify-between gap-3 border-t border-white/10 pt-4"><div><p className="text-xs uppercase tracking-wide text-slate-500">Model pick</p><p className="font-bold text-cyan-100">{game.winner?`${game.winner} · ${(game.winProbability*100).toFixed(1)}%`:'Unavailable'}</p></div><p className="text-sm text-slate-400">{game.venue||'Venue TBD'}</p></div></Link>)}</div>}</main>}
