"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Library, PauseCircle, PlayCircle, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import GlowCard from "@/components/ui/GlowCard";
import SocialQueue from "@/components/internal/social/SocialQueue";
import SocialPerformance from "@/components/internal/social/SocialPerformance";
import SocialSettings from "@/components/internal/social/SocialSettings";
import SocialStatus, { StatusPill } from "@/components/internal/social/SocialStatus";
import SocialHistory from "@/components/internal/social/SocialHistory";
import { api } from "@/lib/api";

const EMPTY = "—";
const fmt = (value) => value ? new Date(value).toLocaleString() : EMPTY;

function ContentStudio({ detail, busy, onClose, onSave, onCaption, onMedia, onTemplate }) {
  const [caption, setCaption] = useState(detail.content || "");
  const media = detail.media?.[0];
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/90 p-4 backdrop-blur" role="dialog" aria-modal="true" aria-label="Content Studio">
    <div className="mx-auto max-w-5xl rounded-3xl border border-cyan-400/20 bg-[#08111d] p-6 shadow-2xl">
      <div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Content Studio</p><h2 className="mt-1 text-2xl font-black">{detail.post_type?.replaceAll("_", " ") || detail.category}</h2></div><button onClick={onClose} className="btn btn-glass px-4 py-2">Close</button></div>
      <div className="mt-6 grid gap-6 lg:grid-cols-2">
        <div>{media?.previewUrl ? <div className="relative aspect-video overflow-hidden rounded-2xl bg-slate-950"><Image src={media.previewUrl} alt={media.alt_text || "Social media preview"} fill sizes="(max-width: 1024px) 100vw, 50vw" unoptimized className="object-cover" /></div> : <div className="flex aspect-video items-center justify-center rounded-2xl bg-white/[.04] text-sm text-slate-500">No generated media</div>}
          <dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Source freshness</dt><dd>{fmt(detail.evidence?.source_timestamp)}</dd></div><div><dt className="text-slate-500">Media provider</dt><dd>{media?.provider || "Deterministic / none"}</dd></div><div><dt className="text-slate-500">Model probability</dt><dd>{detail.source_context?.model_probability != null ? `${(detail.source_context.model_probability * 100).toFixed(1)}%` : EMPTY}</dd></div><div><dt className="text-slate-500">Market probability</dt><dd>{detail.source_context?.market_probability != null ? `${(detail.source_context.market_probability * 100).toFixed(1)}%` : EMPTY}</dd></div></dl>
        </div>
        <div><label className="text-xs font-black uppercase tracking-wider text-slate-400">Final X caption<textarea value={caption} onChange={(event) => setCaption(event.target.value)} maxLength={280} rows={9} className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950 p-4 text-sm leading-6 text-white" /></label><p className="mt-1 text-right text-xs text-slate-500">{caption.length}/280</p>
          <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => onSave(detail.post_id, caption)} disabled={busy} className="btn btn-primary px-4 py-2">Save validated caption</button><button onClick={() => onCaption(detail.post_id)} disabled={busy} className="btn btn-glass px-4 py-2">Regenerate caption</button><button onClick={() => onMedia(detail.post_id, "image")} disabled={busy} className="btn btn-glass px-4 py-2">New image version</button><button onClick={() => onMedia(detail.post_id, "video")} disabled={busy} className="btn btn-glass px-4 py-2">New video version</button></div>
          <label className="mt-4 block text-xs font-black uppercase tracking-wider text-slate-400">Compatible template<select defaultValue={detail.post_type} onChange={(event) => onTemplate(detail.post_id, event.target.value)} disabled={busy} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-white">{["AI_PICK", "GAME_PREVIEW", "ENGAGEMENT_QUESTION", "MODEL_VS_MARKET", "UPSET_WATCH", "LINE_MOVEMENT", "WIN_RECEIPT", "CASHED", "LOSS_RECEIPT", "MISS", "DAILY_RECAP", "WEEKLY_REPORT", "MODEL_RECAP"].map((name) => <option key={name}>{name}</option>)}</select></label>
          <details className="mt-5 rounded-xl bg-white/[.04] p-4 text-xs text-slate-400"><summary className="cursor-pointer font-black uppercase tracking-wider">Evidence and integrity</summary><pre className="mt-3 overflow-x-auto whitespace-pre-wrap">{JSON.stringify({ event: detail.event_type, game: detail.game_id, sourceHash: detail.source_hash, score: detail.score, reasons: detail.score_reasons }, null, 2)}</pre></details>
        </div>
      </div>
    </div>
  </div>;
}

export default function SocialOperationsPage() {
  const [state, setState] = useState({ summary: {}, queue: [], skipped: [], media: [], analytics: {}, history: [], engagement: [] });
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [detail, setDetail] = useState(null);
  const load = useCallback(async () => {
    setError("");
    try {
      const [summary, queue, skipped, media, analytics, history, engagement] = await Promise.all([api.internal.social.summary(), api.internal.social.queue(), api.internal.social.skipped(), api.internal.social.media(), api.internal.social.analytics(), api.internal.socialPosts({ limit: 50 }), api.internal.social.engagement()]);
      setState({ summary, queue: queue.items || [], skipped: skipped.items || [], media: media.items || [], analytics, history: history.items || [], engagement: engagement.items || [] });
    } catch (exception) { setError(exception.message); } finally { setLoading(false); }
  }, []);
  useEffect(() => { load(); }, [load]);
  const run = useCallback(async (request, message = "Social operation completed.") => { setBusy(true); setError(""); setNotice(""); try { await request(); setNotice(message); await load(); } catch (exception) { setError(exception.message); } finally { setBusy(false); } }, [load]);
  const preview = async (postId) => { setBusy(true); try { setDetail(await api.internal.social.post(postId)); } catch (exception) { setError(exception.message); } finally { setBusy(false); } };
  const caption = (postId) => run(() => api.internal.social.regenerateCaption(postId), "Caption regenerated and revalidated.");
  const media = (postId, mediaType) => run(() => api.internal.social.regenerateMedia(postId, mediaType), `${mediaType} version generated.`);
  const settings = state.summary.settings || {};
  if (loading) return <main className="mx-auto min-h-screen max-w-7xl px-6 py-16">Loading Social Operations…</main>;
  return <main className="mx-auto min-h-screen max-w-7xl px-4 py-8 sm:px-6 lg:py-12">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/internal/operations" className="inline-flex items-center gap-2 text-sm font-bold text-cyan-300"><ArrowLeft size={16} /> Command Center</Link><p className="mt-5 text-xs font-black uppercase tracking-[.24em] text-emerald-300">Owner-only control room</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Social Operations</h1><p className="mt-3 max-w-3xl text-slate-400">Grounded SmartBetSports events, branded media, publishing safety, receipts, and real X performance in one place.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => run(api.internal.social.discover, "New verified opportunities discovered.")} disabled={busy} className="btn btn-glass inline-flex items-center gap-2 px-4 py-3"><Sparkles size={17} /> Discover</button><button onClick={() => run(api.internal.social.process, "Due queue items processed.")} disabled={busy} className="btn btn-glass inline-flex items-center gap-2 px-4 py-3"><PlayCircle size={17} /> Process Queue</button><button onClick={() => run(settings.paused ? api.internal.social.resume : api.internal.social.pause, settings.paused ? "Social discovery resumed; publishing gates remain unchanged." : "All social activity paused.")} disabled={busy} className="inline-flex items-center gap-2 rounded-xl border border-rose-400/40 bg-rose-400/10 px-4 py-3 font-black text-rose-100">{settings.paused ? <PlayCircle size={18} /> : <PauseCircle size={18} />}{settings.paused ? "Resume Social" : "PAUSE ALL SOCIAL"}</button></div></div>
    {(error || notice) && <div role={error ? "alert" : "status"} className={`mt-6 rounded-xl border p-4 text-sm ${error ? "border-rose-400/30 bg-rose-400/10 text-rose-100" : "border-emerald-400/30 bg-emerald-400/10 text-emerald-100"}`}>{error || notice}</div>}
    <section className="mt-8"><SocialStatus summary={state.summary} /><p className="mt-3 text-xs text-slate-500">Last publish: {fmt(state.summary.lastPublish)} · Next scheduled: {fmt(state.summary.nextScheduledPost?.scheduled_at)} · Source: {fmt(state.summary.latestSourceAt)}</p></section>
    <section className="mt-10"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Live Queue</p><h2 className="mt-1 text-2xl font-black">Ready, generating, and review items</h2></div><button onClick={load} className="btn btn-glass inline-flex items-center gap-2 px-3 py-2"><RefreshCw size={15} /> Refresh</button></div><SocialQueue items={state.queue} busy={busy} onPreview={preview} onCaption={caption} onMedia={media} onPublish={(postId) => run(() => api.internal.social.publish(postId), settings.dry_run ? "Dry run confirmed: no public X write was made." : "Publish request completed.")} onReschedule={(id) => run(() => api.internal.social.reschedule(id, new Date(Date.now() + 3600000).toISOString()), "Opportunity moved one hour later.")} onCancel={(id) => run(() => api.internal.social.cancel(id), "Opportunity skipped.")} /></section>
    <section className="mt-10 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><GlowCard className="p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-300" /><div><p className="text-xs font-black uppercase tracking-wider text-emerald-300">Automation Controls</p><h2 className="text-2xl font-black">Safe rollout settings</h2></div></div><div className="mt-5"><SocialSettings settings={settings} busy={busy} onChange={(update) => run(() => api.internal.social.updateSettings(update), "Setting saved and audited.")} /></div></GlowCard>
      <SocialPerformance analytics={state.analytics} busy={busy} onRefresh={() => run(api.internal.social.refreshMetrics, "Available X metrics refreshed.")} /></section>
    <section className="mt-10 grid gap-5 lg:grid-cols-2"><GlowCard className="p-6"><p className="text-xs font-black uppercase tracking-wider text-amber-300">Skipped Opportunities</p><h2 className="mt-1 text-2xl font-black">Why the engine stayed quiet</h2><div className="mt-5 space-y-3">{state.skipped.length ? state.skipped.map((item) => <div key={item.opportunity_id} className="rounded-xl bg-white/[.04] p-4"><div className="flex justify-between gap-3"><p className="font-bold">{item.matchup} · {item.content_type?.replaceAll("_", " ")}</p><span className="text-sm text-amber-200">{item.score}/{item.threshold}</span></div><p className="mt-2 text-xs text-slate-400">{item.skip_reason || item.score_reasons?.join(" · ")}</p><p className="mt-2 text-xs text-slate-600">{fmt(item.created_at)}</p></div>) : <p className="text-sm text-slate-400">No skipped opportunities recorded.</p>}</div></GlowCard>
      <GlowCard className="p-6"><div className="flex items-center gap-3"><Library className="text-cyan-300" /><div><p className="text-xs font-black uppercase tracking-wider text-cyan-300">Media Library</p><h2 className="text-2xl font-black">Generated versions</h2></div></div><div className="mt-5 grid grid-cols-2 gap-3">{state.media.slice(0, 8).map((asset) => <div key={asset.media_asset_id} className="overflow-hidden rounded-xl bg-white/[.04]">{asset.previewUrl && asset.media_type === "image" ? <div className="relative aspect-video"><Image src={asset.previewUrl} alt={asset.alt_text || "Generated social media"} fill sizes="25vw" unoptimized className="object-cover" /></div> : <div className="flex aspect-video items-center justify-center text-xs uppercase text-slate-500">{asset.media_type}</div>}<div className="p-3"><p className="text-xs font-black">{asset.template?.replaceAll("_", " ")} · v{asset.version}</p><p className="mt-1 text-[11px] text-slate-500">{fmt(asset.generated_at)} · {asset.published ? "Published" : "Not published"}</p><div className="mt-2"><StatusPill status={asset.status} /></div></div></div>)}</div></GlowCard></section>
    <section className="mt-10"><GlowCard className="p-6"><p className="text-xs font-black uppercase tracking-wider text-emerald-300">Engagement Approval Queue</p><h2 className="mt-1 text-2xl font-black">Relevant replies, never bulk outreach</h2><p className="mt-2 text-sm text-slate-400">External proactive replies stay off by default. Candidates require fresh verified game evidence and owner approval.</p><div className="mt-5 space-y-3">{state.engagement.length ? state.engagement.map((item) => <div key={item.engagement_id} className="rounded-xl bg-white/[.04] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-bold">{item.kind.replaceAll("_", " ")}</p><StatusPill status={item.status} /></div><p className="mt-2 text-sm text-slate-300">{item.candidate_text}</p>{item.status === "REVIEW" && <div className="mt-3 flex gap-2"><button onClick={() => run(() => api.internal.social.decideEngagement(item.engagement_id, "approve"), "Reply candidate approved for the controlled queue.")} className="btn btn-primary px-3 py-2 text-xs">Approve</button><button onClick={() => run(() => api.internal.social.decideEngagement(item.engagement_id, "reject"), "Reply candidate rejected.")} className="btn btn-glass px-3 py-2 text-xs">Reject</button></div>}</div>) : <p className="rounded-xl bg-white/[.04] p-4 text-sm text-slate-400">No reply candidates need review.</p>}</div></GlowCard></section>
    <section className="mt-10"><SocialHistory items={state.history} /></section>
    {detail && <ContentStudio detail={detail} busy={busy} onClose={() => setDetail(null)} onSave={(postId, text) => run(() => api.internal.social.editCaption(postId, text), "Caption saved after grounding validation.").then?.(() => setDetail(null))} onCaption={caption} onMedia={media} onTemplate={(postId, template) => run(() => api.internal.social.changeTemplate(postId, template), "Compatible template applied and caption revalidated.")} />}
  </main>;
}
