-- Durable state for a bounded Supabase Cron -> Vercel REST automation.
-- No policies are intentionally created: only the direct server connection may
-- read or write these operational tables.
create table if not exists public.nfl_automation_state (
  singleton integer primary key check (singleton = 1),
  enabled integer not null default 1,
  active_experiment_key text,
  last_context_refresh_at text,
  last_tick_started_at text,
  last_tick_completed_at text,
  last_status text not null default 'BOOTSTRAP',
  last_error_code text,
  last_provider_contact_at text,
  next_due_at text,
  updated_at text not null
);

create table if not exists public.nfl_capture_experiments (
  experiment_key text primary key,
  season integer not null,
  season_type text not null check (season_type in ('preseason','regular','postseason')),
  display_week integer not null,
  provider_week integer not null,
  status text not null,
  manifest_json text not null,
  manifest_hash text not null,
  credits_limit integer not null check (credits_limit >= 3),
  credits_reserved integer not null default 0 check (credits_reserved >= 0),
  provider_remaining integer,
  quota_state text not null default 'BOOTSTRAP',
  created_at text not null,
  sealed_at text,
  unique (season, season_type, display_week)
);

create table if not exists public.nfl_capture_games (
  experiment_key text not null references public.nfl_capture_experiments(experiment_key),
  game_id text not null,
  home_team text not null,
  away_team text not null,
  kickoff text not null,
  kickoff_epoch double precision not null,
  schedule_hash text not null,
  status text not null default 'SCHEDULED',
  primary key (experiment_key, game_id)
);

create table if not exists public.nfl_capture_checkpoints (
  experiment_key text not null,
  game_id text not null,
  offset_minutes integer not null,
  due_at text not null,
  due_epoch double precision not null,
  deadline_at text not null,
  deadline_epoch double precision not null,
  state text not null default 'PENDING',
  attempt_count integer not null default 0,
  last_attempt_at text,
  primary key (experiment_key, game_id, offset_minutes),
  foreign key (experiment_key, game_id)
    references public.nfl_capture_games(experiment_key, game_id)
);

create table if not exists public.nfl_capture_requests (
  id bigint generated by default as identity primary key,
  request_key text not null unique,
  experiment_key text not null references public.nfl_capture_experiments(experiment_key),
  requested_at text not null,
  completed_at text,
  state text not null,
  credits_reserved integer not null,
  remaining integer,
  used integer,
  last_cost integer,
  response_hash text,
  http_status integer
);

create table if not exists public.nfl_capture_markets (
  capture_key text primary key,
  experiment_key text not null,
  game_id text not null,
  offset_minutes integer not null,
  request_id bigint not null references public.nfl_capture_requests(id),
  retrieved_at text not null,
  stored_at text not null,
  kickoff text not null,
  cutoff_epoch double precision not null,
  deadline_epoch double precision not null,
  event_id text not null,
  bookmaker text not null,
  market_type text not null check (market_type in ('h2h','spreads','totals')),
  source_time text not null,
  source_epoch double precision not null,
  retrieved_epoch double precision not null,
  outcomes_json text not null,
  provenance_json text not null,
  unique (experiment_key, game_id, offset_minutes, bookmaker, market_type),
  foreign key (experiment_key, game_id, offset_minutes)
    references public.nfl_capture_checkpoints(experiment_key, game_id, offset_minutes)
);

create table if not exists public.nfl_capture_quotes (
  capture_key text not null references public.nfl_capture_markets(capture_key),
  side text not null,
  line double precision,
  price double precision not null,
  primary key (capture_key, side)
);

create table if not exists public.nfl_automation_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  severity text not null,
  category text not null,
  state text not null,
  summary text not null,
  experiment_key text,
  game_id text,
  detected_at text not null,
  details_json text not null
);

insert into public.nfl_automation_state(singleton, enabled, last_status, updated_at)
values (1, 1, 'BOOTSTRAP', now()::text)
on conflict (singleton) do nothing;

alter table public.nfl_automation_state enable row level security;
alter table public.nfl_capture_experiments enable row level security;
alter table public.nfl_capture_games enable row level security;
alter table public.nfl_capture_checkpoints enable row level security;
alter table public.nfl_capture_requests enable row level security;
alter table public.nfl_capture_markets enable row level security;
alter table public.nfl_capture_quotes enable row level security;
alter table public.nfl_automation_events enable row level security;

revoke all on table public.nfl_automation_state from anon, authenticated;
revoke all on table public.nfl_capture_experiments from anon, authenticated;
revoke all on table public.nfl_capture_games from anon, authenticated;
revoke all on table public.nfl_capture_checkpoints from anon, authenticated;
revoke all on table public.nfl_capture_requests from anon, authenticated;
revoke all on table public.nfl_capture_markets from anon, authenticated;
revoke all on table public.nfl_capture_quotes from anon, authenticated;
revoke all on table public.nfl_automation_events from anon, authenticated;

create schema if not exists smartbets_internal;
revoke all on schema smartbets_internal from public;

create or replace function smartbets_internal.block_immutable_capture()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  raise exception 'immutable NFL market evidence';
end
$$;

create or replace function smartbets_internal.enforce_pregame_capture()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if extract(epoch from clock_timestamp()) >= new.cutoff_epoch
     or new.retrieved_epoch >= new.cutoff_epoch
     or new.source_epoch >= new.cutoff_epoch
     or new.source_epoch > new.retrieved_epoch
     or extract(epoch from clock_timestamp()) >= new.deadline_epoch
     or new.retrieved_epoch >= new.deadline_epoch then
    raise exception 'pregame write boundary';
  end if;
  return new;
end
$$;

create or replace function smartbets_internal.enforce_pregame_quote()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  evidence_cutoff double precision;
  evidence_deadline double precision;
begin
  select cutoff_epoch, deadline_epoch
    into evidence_cutoff, evidence_deadline
    from public.nfl_capture_markets
   where capture_key = new.capture_key;
  if evidence_cutoff is null
     or extract(epoch from clock_timestamp()) >= evidence_cutoff
     or extract(epoch from clock_timestamp()) >= evidence_deadline then
    raise exception 'pregame write boundary';
  end if;
  return new;
end
$$;

create or replace function smartbets_internal.protect_nfl_experiment()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  if old.manifest_json is distinct from new.manifest_json
     or old.manifest_hash is distinct from new.manifest_hash
     or old.season is distinct from new.season
     or old.season_type is distinct from new.season_type
     or old.display_week is distinct from new.display_week
     or old.provider_week is distinct from new.provider_week
     or old.credits_limit is distinct from new.credits_limit then
    raise exception 'immutable NFL experiment manifest';
  end if;
  return new;
end
$$;

drop trigger if exists nfl_capture_markets_pregame on public.nfl_capture_markets;
create trigger nfl_capture_markets_pregame
before insert on public.nfl_capture_markets
for each row execute function smartbets_internal.enforce_pregame_capture();

drop trigger if exists nfl_capture_quotes_pregame on public.nfl_capture_quotes;
create trigger nfl_capture_quotes_pregame
before insert on public.nfl_capture_quotes
for each row execute function smartbets_internal.enforce_pregame_quote();

drop trigger if exists nfl_capture_markets_immutable_update on public.nfl_capture_markets;
create trigger nfl_capture_markets_immutable_update
before update on public.nfl_capture_markets
for each row execute function smartbets_internal.block_immutable_capture();

drop trigger if exists nfl_capture_markets_immutable_delete on public.nfl_capture_markets;
create trigger nfl_capture_markets_immutable_delete
before delete on public.nfl_capture_markets
for each row execute function smartbets_internal.block_immutable_capture();

drop trigger if exists nfl_capture_quotes_immutable_update on public.nfl_capture_quotes;
create trigger nfl_capture_quotes_immutable_update
before update on public.nfl_capture_quotes
for each row execute function smartbets_internal.block_immutable_capture();

drop trigger if exists nfl_capture_quotes_immutable_delete on public.nfl_capture_quotes;
create trigger nfl_capture_quotes_immutable_delete
before delete on public.nfl_capture_quotes
for each row execute function smartbets_internal.block_immutable_capture();

drop trigger if exists nfl_capture_experiments_protect on public.nfl_capture_experiments;
create trigger nfl_capture_experiments_protect
before update on public.nfl_capture_experiments
for each row execute function smartbets_internal.protect_nfl_experiment();

drop trigger if exists nfl_capture_games_immutable_update on public.nfl_capture_games;
create trigger nfl_capture_games_immutable_update
before update on public.nfl_capture_games
for each row execute function smartbets_internal.block_immutable_capture();

drop trigger if exists nfl_capture_games_immutable_delete on public.nfl_capture_games;
create trigger nfl_capture_games_immutable_delete
before delete on public.nfl_capture_games
for each row execute function smartbets_internal.block_immutable_capture();
