-- Server-only NFL production lifecycle. Safe to rerun; source predictions stay immutable.
create table if not exists public.nfl_prediction_history (
  id bigint generated by default as identity primary key, prediction_id bigint not null unique,
  user_id bigint not null, sport text not null, league text not null, season integer not null,
  season_type text not null, week integer not null, game_id text not null, kickoff_time text not null,
  away_team text, home_team text, predicted_winner text not null, model_probability double precision,
  betting_edge double precision, market_odds integer, model_version text not null, data_version text,
  generated_at text not null, source_provider text, frozen_prediction_hash text not null,
  settlement_status text not null default 'PENDING', away_score integer, home_score integer,
  actual_winner text, final_provider text, final_source_timestamp text, settled_at text,
  settlement_reason text, created_at text not null, updated_at text not null
);
create table if not exists public.nfl_game_result_snapshots (
  id bigint generated by default as identity primary key, game_id text not null unique,
  season integer not null, season_type text not null, week integer not null, kickoff_time text not null,
  away_team text not null, home_team text not null, away_score integer, home_score integer,
  game_status text not null, team_stats_json text not null, player_stats_json text not null,
  provider text not null, provider_timestamp text, retrieved_at text not null, source_hash text not null
);
create table if not exists public.nfl_sgp_benchmarks (
  id bigint generated by default as identity primary key, benchmark_key text not null unique,
  game_id text not null, season integer not null, season_type text not null, week integer not null,
  profile text not null, generated_at text not null, kickoff_time text not null, model_version text not null,
  data_version text, source_prediction_id bigint, source_hash text not null, ticket_status text not null,
  no_bet_reason text, combined_odds integer, estimated_probability double precision,
  recommendation_score double precision, legs_json text not null, graded_at text,
  unique(game_id, profile, model_version)
);
create table if not exists public.nfl_sgp_benchmark_legs (
  id bigint generated by default as identity primary key, benchmark_id bigint not null,
  leg_index integer not null, market_type text not null, player text, team text, side text,
  line double precision, odds integer, model_probability double precision,
  recommendation_score double precision, metadata_json text not null,
  result_status text not null default 'PENDING', actual_value double precision, graded_at text,
  unique(benchmark_id, leg_index)
);
create table if not exists public.nfl_production_audits (
  id bigint generated by default as identity primary key, audit_id text not null unique,
  league text not null, season integer not null, season_type text not null, week integer not null,
  result text not null, critical_errors integer not null, warnings integer not null,
  report_json text not null, created_at text not null
);
create index if not exists idx_nfl_prediction_history_week on public.nfl_prediction_history(season,season_type,week,game_id);
create index if not exists idx_nfl_prediction_history_user on public.nfl_prediction_history(user_id,settlement_status,generated_at);
create index if not exists idx_nfl_sgp_benchmark_week on public.nfl_sgp_benchmarks(season,season_type,week,profile,ticket_status);
create index if not exists idx_nfl_sgp_leg_market on public.nfl_sgp_benchmark_legs(market_type,result_status);
create index if not exists idx_nfl_production_audit_week on public.nfl_production_audits(season,season_type,week,created_at);
alter table public.nfl_prediction_history enable row level security;
alter table public.nfl_game_result_snapshots enable row level security;
alter table public.nfl_sgp_benchmarks enable row level security;
alter table public.nfl_sgp_benchmark_legs enable row level security;
alter table public.nfl_production_audits enable row level security;
revoke all on table public.nfl_prediction_history, public.nfl_game_result_snapshots,
  public.nfl_sgp_benchmarks, public.nfl_sgp_benchmark_legs, public.nfl_production_audits
  from anon, authenticated;

alter table public.parlay_history add column if not exists game_id text;
alter table public.parlay_history add column if not exists season integer;
alter table public.parlay_history add column if not exists season_type text;
alter table public.parlay_history add column if not exists week integer;
alter table public.parlay_history add column if not exists kickoff_time text;
alter table public.parlay_history add column if not exists settled_at text;
alter table public.parlay_history add column if not exists source_type text default 'USER';
alter table public.parlay_history add column if not exists game_ids_json text;
